gText_Oak_Welcome::
	.string "이야- 오래 기다리게 했구나!\p"
	.string "포켓몬스터의 세계에\n"
	.string "잘 왔다!\p"
	.string "내 이름은 오박사\p"
	.string "모두에게는 포켓몬 박사라고\n"
	.string "알려져 있단다\p"
	.string "$"

gText_Oak_Pokemon::
	.string "포켓몬스터\n"
	.string "...줄여서 포켓몬\p"
	.string "\n"
	.string "$"

gText_Oak_MainSpeech::
	.string "이 세계에는\n"
	.string "포켓몬이라 불리는 생명체가\l"
	.string "도처에 살고 있다!\p"
	.string "사람은 포켓몬과\n"
	.string "사이좋게 지내거나\l"
	.string "함께 싸우거나...\l"
	.string "서로 도와가며\l"
	.string "살아가고 있단다\p"
	.string "하지만 우리는 포켓몬에 대해\n"
	.string "모든 것을 알고 있지는 않다\p"
	.string "포켓몬의 비밀은\n"
	.string "아직도 많이 있어!\p"
	.string "나는 그 비밀을 풀기 위해\n"
	.string "매일 연구를\l"
	.string "계속하고 있는 것이란다!\p"
	.string "$"

gText_Oak_AndYouAre::
	.string "그건 그렇고...$"

gText_Oak_BoyOrGirl::
	.string "자네는 남자인가?\n"
	.string "아니면 여자인가?$"

gText_Oak_WhatChallenge::
	.string "어떤 도전을\n"
	.string "기대하고 있는가?$"

gText_Oak_ChallengeSelected::
	.string "그거라면 자네에게 딱 알맞은\n"
	.string "수준의 도전이 될 것 같구나!$" 

gText_Oak_WhatsYourName::
	.string "그럼 이름을 알려주게나!$"

gText_Oak_SoItsPlayer::
	.string "{PLAYER}{K_I}로구나?$"

gText_Oak_YourePlayer::
	.string "{PLAYER}{K_I}!!\n"
	.string "준비는 되었는가?\n"
	.string "드디어 이제부터\n"
	.string "너만의 이야기가 시작된다!\p"
	.string "$"

gText_Oak_AreYouReady::
	.string "즐거운 일도 괴로운 일도\n"
	.string "한가득 너를 기다리고 있겠지!\p"
	.string "꿈과 모험과!\n"
	.string "포켓몬스터의 세계로!\l"
	.string "레츠 고-!\p"
	.string "그럼 다음에 다시 만나자!\p"
	.string "$"
