gText_Oak_LateNight::
	.string "..... ..... .....\n"
	.string "..... ..... .....\p"
	.string "으-음 음냐 음냐...\n"
	.string "..... ..... .....\p"
	.string "오잉? 이런 시간에\n"
	.string "손님이 왔는가...\p"
	.string "$"

gText_Oak_Morning::
	.string "..... ..... .....\n"
	.string "..... ..... .....\p"
	.string "으-음 음냐 음냐...\n"
	.string "..... ..... .....\p"
	.string "오잉? 밖은 완전히\n"
	.string "밝아져 있지 않은가!\p"
	.string "$"	

gText_Oak_Day::
	.string "..... ..... .....\n"
	.string "..... ..... .....\p"
	.string "으-음 음냐 음냐...\n"
	.string "..... ..... .....\p"
	.string "뭐야! 벌써 시간이 이렇게 됐나!\n"
	.string "이런! 마냥 잠만 잔 것 같군!\p"
	.string "$"	

gText_Oak_Evening::
	.string "..... ..... .....\n"
	.string "..... ..... .....\p"
	.string "흐음 슬슬\n"
	.string "해가 질 시간이 왔구나...\p"
	.string "...라며 넋 놓고 있을 때가\n"
	.string "아니구나!\p"
	.string "$"	

gText_Oak_Night::
	.string "..... ..... .....\n"
	.string "..... ..... .....\p"
	.string "흐음 흐음 흠흠...\n"
	.string "..... ..... .....\p"
	.string "음? 어허 이런 미안 미안!\p"
	.string "지금 책을 읽고 있었단다\p"
	.string "$"	

gText_Oak_Welcome::
	.string "이야- 오래 기다리게 했구나!\p"
	.string "포켓몬스터의 세계에\n"
	.string "잘 왔다!\p"
	.string "내 이름은 오박사\p"
	.string "모두에게는 포켓몬 박사라고\n"
	.string "알려져 있단다\p"
	.string "그건 그렇고 너는\n"
	.string "모험이 처음인 게냐?\p"
	.string "우선 내가\n"
	.string "이 세계에 대한 것을 가르쳐주마!\p"
	.string "$"

gText_Oak_Pokemon::
	.string "이 세계에는 포켓몬스터\n"
	.string "...줄여서 포켓몬이라\l"
	.string "불리는 생명체가\l"
	.string "도처에 살고 있다!\p"
	.string "\n"
	.string "$"

gText_Oak_MainSpeech::
	.string "우리 인간은\n"
	.string "포켓몬과 사이좋게 살고 있지\p"
	.string "함께 놀기도 하고\n"
	.string "힘을 합쳐 일하기도 하고\p"
	.string "그리고 포켓몬끼리 싸우게 하여\n"
	.string "유대감을 돈독히 다지기도 하고...\p"
	.string "나는 그런 포켓몬들을\n"
	.string "자세히 알기 위해\p"
	.string "매일 연구를\n"
	.string "계속하고 있는 것이란다!\p"
	.string "$"

gText_Oak_AndYouAre::
	.string "그건 그렇고...이제 슬슬\n"
	.string "자네에 대해 알아보도록 하지!$"

gText_Oak_BoyOrGirl::
	.string "자네는 남자인가?\n"
	.string "아니면 여자인가?\l"
	.string "어느 쪽인가를 알려주게나$"

gText_Oak_WhatChallenge::
	.string "어느 정도의 도전을\n"
	.string "원하는지도 알려주게나$"

gText_Oak_ChallengeSelected::
	.string "챌린지 설정이 완료되었습니다!\n$"

gText_Oak_WhatsYourName::
	.string "그럼 이름을 알려주게나!$"

gText_Oak_SoItsPlayer::
	.string "{PLAYER}{K_I}로구나?$"

gText_Oak_YourePlayer::
	.string "{PLAYER}!!\n"
	.string "준비는 되었는가?\n"
	.string "드디어 이제부터\n"
	.string "너만의 이야기가 시작된다!\p"
	.string "$"

gText_Oak_AreYouReady::
	.string "즐거운 일도 괴로운 일도\n"
	.string "한가득 너를 기다리고 있겠지!\p"
	.string "꿈과 모험과!\n"
	.string "포켓몬스터의 세계로!\l"
	.string "레츠 고-!\p"
	.string "그럼 다음에 다시 만나자!\p"
	.string "$"
