#include "global.h"
#include "strings.h"
#include "battle_pyramid_bag.h"
#include "item_menu.h"

ALIGNED(4)
const u8 gText_ExpandedPlaceholder_Empty[] = _("");
const u8 gText_ExpandedPlaceholder_Kun[] = _("군");
const u8 gText_ExpandedPlaceholder_Chan[] = _("양");
const u8 gText_ExpandedPlaceholder_Sapphire[] = _("사파이어");
const u8 gText_ExpandedPlaceholder_Ruby[] = _("루비");
const u8 gText_ExpandedPlaceholder_Emerald[] = _("에메랄드");
const u8 gText_ExpandedPlaceholder_Aqua[] = _("아쿠아");
const u8 gText_ExpandedPlaceholder_Magma[] = _("마그마");
const u8 gText_ExpandedPlaceholder_Archie[] = _("아강");
const u8 gText_ExpandedPlaceholder_Maxie[] = _("마적");
const u8 gText_ExpandedPlaceholder_Kyogre[] = _("가이오가");
const u8 gText_ExpandedPlaceholder_Groudon[] = _("그란돈");
const u8 gText_ExpandedPlaceholder_Brendan[] = _("휘웅");
const u8 gText_ExpandedPlaceholder_May[] = _("봄이");
const u8 gText_ExpandedPlaceholder_Red[] = _("레드");
const u8 gText_ExpandedPlaceholder_Green[] = _("그린");
const u8 gText_ExpandedPlaceholder_Silver[] = _("실버");
const u8 gText_ExpandedPlaceholder_BoyCallMale[] = _("형");
const u8 gText_ExpandedPlaceholder_BoyCallFemale[] = _("누나");
const u8 gText_ExpandedPlaceholder_GirlCallMale[] = _("오빠");
const u8 gText_ExpandedPlaceholder_GirlCallFemale[] = _("언니");
const u8 gText_ExpandedPlaceholder_Eun[] = _("은");
const u8 gText_ExpandedPlaceholder_Neun[] = _("는");
const u8 gText_ExpandedPlaceholder_Eu[] = _("으");
const u8 gText_ExpandedPlaceholder_I[] = _("이");
const u8 gText_ExpandedPlaceholder_Ga[] = _("가");
const u8 gText_ExpandedPlaceholder_Eul[] = _("을");
const u8 gText_ExpandedPlaceholder_Reul[] = _("를");
const u8 gText_ExpandedPlaceholder_Wa[] = _("와");
const u8 gText_ExpandedPlaceholder_Gwa[] = _("과");
const u8 gText_ExpandedPlaceholder_A[] = _("아");
const u8 gText_ExpandedPlaceholder_Ya[] = _("야");
const u8 gText_EggNickname[POKEMON_NAME_LENGTH + 1] = _("알");
const u8 gText_Pokemon[POKEMON_NAME_LENGTH + 1] = _("포켓몬");
const u8 gText_Player[] = _("주인공"); // Unused
const u8 gText_Pokedex[] = _("포켓몬 도감"); // Unused
const u8 gText_Time[] = _("플레이 시간");
const u8 gText_Badges[] = _("가지고 있는 배지"); // Unused
const u8 gText_AButton[] = _("A 버튼"); // Unused
const u8 gText_BButton[] = _("B 버튼"); // Unused
const u8 gText_RButton[] = _("R 버튼"); // Unused
const u8 gText_LButton[] = _("L 버튼"); // Unused
const u8 gText_Start[] = _("START"); // Unused
const u8 gText_Select[] = _("SELECT"); // Unused
const u8 gText_ControlPad[] = _("십자 버튼"); // Unused
const u8 gText_LButtonRButton[] = _("L 버튼  R 버튼"); // Unused
const u8 gText_Controls[] = _("조작 설명"); // Unused
ALIGNED(4) const u8 gText_PickOk[] = _("{DPAD_UPDOWN}선택한다 {A_BUTTON}결정"); // Unused
ALIGNED(4) const u8 gText_Next[] = _("{A_BUTTON}음");
ALIGNED(4) const u8 gText_NextBack[] = _("{A_BUTTON}다음 {B_BUTTON}취소");
ALIGNED(4) const u8 gText_PickNextCancel[] = _("{DPAD_UPDOWN}선택한다 {A_BUTTON}다음 {B_BUTTON}끝낸다");
ALIGNED(4) const u8 gText_PickCancel[] = _("{DPAD_UPDOWN}선택한다 {A_BUTTON}{B_BUTTON}끝낸다");
ALIGNED(4) const u8 gText_AButtonExit[] = _("{A_BUTTON}끝낸다");
const u8 gText_Boy[] = _("남자");
const u8 gText_Girl[] = _("여자");
const u8 gText_ThisIsAPokemon[] = _("이 세계에는 포켓몬스터\n...줄여서 포켓몬이라\l불리는 생명체가\l도처에 살고 있다!{PAUSE 96}\p");
const u8 gText_5MarksPokemon[] = _("?????  포켓몬");
const u8 gText_UnkHeight[] = _("{CLEAR_TO 0x0C}??'??”");
const u8 gText_UnkHeightMetric[] = _("???.? m");
const u8 gText_UnkWeight[] = _("????.? lbs.");
const u8 gText_UnkWeightMetric[] = _("???.? kg.");
const u8 gText_EmptyPkmnCategory[] = _("                       포켓"); // Unused
const u8 gText_EmptyHeight[] = _("{CLEAR_TO 0x0C}    '    ”"); // Unused
const u8 gText_EmptyWeight[] = _("        .   lbs."); // Unused
const u8 gText_EmptyPokedexInfo1[] = _(""); // Unused
const u8 gText_CryOf1[] = _("의");
const u8 gText_CryOf2[] = _("울음소리");
const u8 gText_EmptyPokedexInfo2[] = _(""); // Unused
const u8 gText_SizeComparedTo[] = _("{K_WAGWA} {PLAYER}의 크기 비교");
const u8 gText_PokedexRegistration[] = _("포켓몬 도감 등록 완료!");
const u8 gText_HTHeight[] = _("키");
const u8 gText_WTWeight[] = _("몸무게");
const u8 gText_SearchingPleaseWait[] = _("검색하고 있습니다...");
const u8 gText_SearchCompleted[] = _("검색이 완료되었습니다!");
const u8 gText_NoMatchingPkmnWereFound[] = _("해당하는 포켓몬이 없습니다...");
const u8 gText_SearchForPkmnBasedOnParameters[] = _("조건을 지정해서\n포켓몬을 검색합니다");
const u8 gText_SwitchPokedexListings[] = _("도감리스트의 순서를 변경합니다");
const u8 gText_ReturnToPokedex[] = _("도감으로 돌아갑니다");
const u8 gText_SelectPokedexMode[] = _("도감 모드를 지정합니다");
const u8 gText_SelectPokedexListingMode[] = _("도감의 순서를 지정합니다");
const u8 gText_ListByFirstLetter[] = _("이름의 첫 글자를 지정합니다\n /발견한 포켓몬만");
const u8 gText_ListByBodyColor[] = _("몸의 색을 지정합니다\n /발견한 포켓몬만");
const u8 gText_ListByType[] = _("타입을 지정합니다\n /잡은 포켓몬만");
const u8 gText_ExecuteSearchSwitch[] = _("검색 또는 변경을 실행합니다");
#if IS_HNS
const u8 gText_DexHoennTitle[] = _("성도도감");
#else
const u8 gText_DexHoennTitle[] = _("호연도감");
#endif
const u8 gText_DexNatTitle[] = _("전국도감");
const u8 gText_DexSortNumericalTitle[] = _("번호순");
const u8 gText_DexSortAtoZTitle[] = _("가나다순");
const u8 gText_DexSortHeaviestTitle[] = _("무거운 순");
const u8 gText_DexSortLightestTitle[] = _("가벼운 순");
const u8 gText_DexSortTallestTitle[] = _("키가 큰 순");
const u8 gText_DexSortSmallestTitle[] = _("키가 작은 순");
const u8 gText_DexSearchAlphaABC[] = _("ABC");
const u8 gText_DexSearchAlphaDEF[] = _("DEF");
const u8 gText_DexSearchAlphaGHI[] = _("GHI");
const u8 gText_DexSearchAlphaJKL[] = _("JKL");
const u8 gText_DexSearchAlphaMNO[] = _("MNO");
const u8 gText_DexSearchAlphaPQR[] = _("PQR");
const u8 gText_DexSearchAlphaSTU[] = _("STU");
const u8 gText_DexSearchAlphaVWX[] = _("VWX");
const u8 gText_DexSearchAlphaYZ[] = _("YZ");
const u8 gText_DexSearchAlpha1[] = _("ㄱㄴ");
const u8 gText_DexSearchAlpha2[] = _("ㄷㄹ");
const u8 gText_DexSearchAlpha3[] = _("ㅁㅂ");
const u8 gText_DexSearchAlpha4[] = _("ㅅㅇ");
const u8 gText_DexSearchAlpha5[] = _("ㅈㅊ");
const u8 gText_DexSearchAlpha6[] = _("ㅋㅌ");
const u8 gText_DexSearchAlpha7[] = _("ㅍㅎ");
const u8 gText_DexSearchColorRed[] = _("빨간색");
const u8 gText_DexSearchColorBlue[] = _("파란색");
const u8 gText_DexSearchColorYellow[] = _("노란색");
const u8 gText_DexSearchColorGreen[] = _("초록색");
const u8 gText_DexSearchColorBlack[] = _("검정색");
const u8 gText_DexSearchColorBrown[] = _("갈색");
const u8 gText_DexSearchColorPurple[] = _("보라색");
const u8 gText_DexSearchColorGray[] = _("회색");
const u8 gText_DexSearchColorWhite[] = _("하얀색");
const u8 gText_DexSearchColorPink[] = _("분홍색");
#if IS_HNS
const u8 gText_DexHoennDescription[] = _("성도지방 포켓몬 도감");
#else
const u8 gText_DexHoennDescription[] = _("호연지방 포켓몬 도감");
#endif
const u8 gText_DexNatDescription[] = _("전국 포켓몬 도감");
const u8 gText_DexSortNumericalDescription[] = _("포켓몬을\n번호순으로 표시합니다");
const u8 gText_DexSortAtoZDescription[] = _("발견한 포켓몬의 이름을\n가나다순으로 표시합니다");
const u8 gText_DexSortHeaviestDescription[] = _("잡은 포켓몬을\n무거운 순서대로 표시합니다");
const u8 gText_DexSortLightestDescription[] = _("잡은 포켓몬을\n가벼운 순서대로 표시합니다");
const u8 gText_DexSortTallestDescription[] = _("잡은 포켓몬을\n키가 큰 순서대로 표시합니다");
const u8 gText_DexSortSmallestDescription[] = _("잡은 포켓몬을\n키가 작은 순서대로 표시합니다");
const u8 gText_DexEmptyString[] = _("");
const u8 gText_DexSearchDontSpecify[] = _("지정하지 않는다");
const u8 gText_DexSearchTypeNone[] = _("없음");
const u8 gText_SelectorArrow[] = _("▶");
const u8 gText_EmptySpace[] = _(" "); // Unused
const u8 gText_WelcomeToHOF[] = _("전당등록을 축하합니다!");
const u8 gText_HOFDexRating[] = _("발견한 포켓몬 {STR_VAR_1}!\n잡은 포켓몬 {STR_VAR_2}!\p털보박사의\n포켓몬 도감 평가!\p털보박사: 어디 보자\p");
const u8 gText_HOFDexSaving[] = _("지금까지의 리포트를 작성하고 있습니다!\n전원을 끄지 마십시오");
const u8 gText_HOFCorrupted[] = _("전당등록의 기록이 손상되었습니다!");
const u8 gText_HOFNumber[] = _("제{STR_VAR_1}회 전당등록!");
const u8 gText_LeagueChamp[] = _("리그 챔피언! 축하합니다!");
const u8 gText_Number[] = _("No. ");
const u8 gText_Level[] = _("Lv. ");
const u8 gText_IdNumberSlash[] = _("IDNo. /"); // Unused
const u8 gText_Name[] = _("이");
const u8 gText_IDNumber[] = _("IDNo.");
const u8 gText_BirchInTrouble[] = _("털보박사님이 위험하다!\n포켓몬을 꺼내서 도와주자!");
const u8 gText_ConfirmStarterChoice[] = _("이 포켓몬으로 결정하겠습니까?");
const u8 gText_Pokemon4[] = _("포켓몬"); // Unused
const u8 gText_FlyToWhere[] = _("어디로 날아갈까요?");
const u8 gMenuText_Use[] = _("쓴다");
const u8 gMenuText_Toss[] = _("버린다");
const u8 gMenuText_Register[] = _("등록");
const u8 gMenuText_Give[] = _("건네준다");
const u8 gMenuText_Confirm[] = _("결정");
const u8 gText_Cancel[] = _("취소");
const u8 gText_Cancel2[] = _("그만둔다");
const u8 gText_EmptyString2[] = _("");
const u8 gText_None[] = _("없음");
const u8 gText_FiveMarks[] = _("?????");
const u8 gText_Slash[] = _("/");
const u8 gText_OneDash[] = _("-");
const u8 gText_TwoDashes[] = _("--");
const u8 gText_ThreeDashes[] = _("---");
const u8 gText_MaleSymbol[] = _("♂");
const u8 gText_FemaleSymbol[] = _("♀");
const u8 gText_LevelSymbol[] = _("{LV}");
const u8 gText_NumberClear01[] = _("{NO}{CLEAR 0x01}");
const u8 gText_RightArrow[] = _("{RIGHT_ARROW}"); // Unused
const u8 gText_IDNumber2[] = _("{ID}{NO}");
const u8 gText_Space[] = _(" ");
const u8 gText_SelectorArrow2[] = _("▶");
const u8 gText_GoBackPrevMenu[] = _("이전으로 돌아갑니다!");
const u8 gText_WhatWouldYouLike[] = _("무엇을 하겠습니까?");
const u8 gMenuText_Give2[] = _("건네준다");
const u8 gText_xVar1[] = _("×{STR_VAR_1}");
const u8 gText_Berry2[] = _(" 열매"); // Unused
const u8 gText_Coins[] = _("{STR_VAR_1}");
const u8 gText_CloseBag[] = _("가방을 닫는다");
const u8 gText_Var1IsSelected[] = _("{STR_VAR_1}{K_EULREUL}\n어떻게 할까요?");
const u8 gText_CantWriteMail[] = _("여기서는 메일을\n쓸 수 없습니다!");
const u8 gText_NoPokemon[] = _("포켓몬이 없습니다!");
const u8 gText_MoveVar1Where[] = _("{STR_VAR_1}{K_EULREUL}\n어디에 넣겠습니까?");
const u8 gText_Var1CantBeHeld[] = _("{STR_VAR_1}{K_EULREUL}\n지니게 할 수 없습니다!");
const u8 gText_TossHowManyVar1s[] = _("{STR_VAR_1}{K_EULREUL}\n몇 개 버리겠습니까?");
const u8 gText_ThrewAwayVar2Var1s[] = _("{STR_VAR_1}{K_EULREUL}\n{STR_VAR_2}개 버렸습니다");
const u8 gText_ConfirmTossItems[] = _("{STR_VAR_1}{K_EULREUL}\n{STR_VAR_2}개 버려도\n괜찮겠습니까?");
#if IS_HNS
    const u8 gText_DadsAdvice[] = _("오박사의 말...\n{PLAYER}! 이런 것은\l쓸 때가 따로 있단다!{PAUSE_UNTIL_PRESS}");
#else
    const u8 gText_DadsAdvice[] = _("아빠의 말...\n{PLAYER}! 이런 것은\l쓸 때가 따로 있단다!{PAUSE_UNTIL_PRESS}");
#endif
const u8 gText_PlayerUsedVar2[] = _("{PLAYER}{K_EUNNEUN}\n{STR_VAR_2}{K_EULREUL} 썼다!{PAUSE_UNTIL_PRESS}");
const u8 gText_RepelEffectsLingered[] = _("아직 전에 썼던\n스프레이의 효과가 남아 있습니다!{PAUSE_UNTIL_PRESS}");
const u8 gText_LureEffectsLingered[] = _("아직 전에 썼던\n코롱의 효과가 남아 있습니다!{PAUSE_UNTIL_PRESS}");
const u8 gText_BoxFull[] = _("박스가 가득 찼습니다!{PAUSE_UNTIL_PRESS}");
const u8 gText_TheField[] = _("필드로");
const u8 gText_TheBattle[] = _("배틀로");
const u8 gText_ThePokemonList[] = _("포켓몬 리스트로");
const u8 gText_TheShop[] = _("숍으로");
const u8 gText_ThePC[] = _("PC로");

const u8 *const gBagMenu_ReturnToStrings[] =
{
    [ITEMMENULOCATION_FIELD]               = gText_TheField,
    [ITEMMENULOCATION_BATTLE]              = gText_TheBattle,
    [ITEMMENULOCATION_PARTY]               = gText_ThePokemonList,
    [ITEMMENULOCATION_SHOP]                = gText_TheShop,
    [ITEMMENULOCATION_BERRY_TREE]          = gText_TheField,
    [ITEMMENULOCATION_BERRY_BLENDER_CRUSH] = gText_TheField,
    [ITEMMENULOCATION_ITEMPC]              = gText_ThePC,
    [ITEMMENULOCATION_FAVOR_LADY]          = gText_TheField,
    [ITEMMENULOCATION_QUIZ_LADY]           = gText_TheField,
    [ITEMMENULOCATION_APPRENTICE]          = gText_TheField,
    [ITEMMENULOCATION_WALLY]               = gText_TheBattle,
    [ITEMMENULOCATION_PCBOX]               = gText_ThePC,
    [ITEMMENULOCATION_BERRY_TREE_MULCH]    = gText_TheField,
};

const u8 *const gPyramidBagMenu_ReturnToStrings[] =
{
    [PYRAMIDBAG_LOC_FIELD]       = gText_TheField,
    [PYRAMIDBAG_LOC_BATTLE]      = gText_TheBattle,
    [PYRAMIDBAG_LOC_PARTY]       = gText_ThePokemonList,
    [PYRAMIDBAG_LOC_CHOOSE_TOSS] = gText_TheField
};

const u8 gText_ReturnToVar1[] = _("{STR_VAR_1}\n돌아갑니다");

const u8 *const gPocketNamesStringsTable[] =
{
    [POCKET_ITEMS] =        COMPOUND_STRING("도구"),
    [POCKET_POKE_BALLS] =   COMPOUND_STRING("몬스터볼"),
    [POCKET_TM_HM]  =       COMPOUND_STRING("기술머신"),
    [POCKET_BERRIES] =      COMPOUND_STRING("나무열매"),
    [POCKET_KEY_ITEMS] =    COMPOUND_STRING("중요한 물건"),
    [POCKET_MEDICINE] =     COMPOUND_STRING("회복"),
#if I_COMBINE_BAG_POCKETS == FALSE
    [POCKET_BATTLE_ITEMS] = COMPOUND_STRING("배틀"),
    [POCKET_TREASURES] =    COMPOUND_STRING("보물"),
#endif
};

const u8 gText_NumberItem_TMBerry[] = _("{NO}{STR_VAR_1}{CLEAR 0x03}{STR_VAR_2}");
const u8 gText_NumberItem_HM[] = _("{CLEAR_TO 0x11}{STR_VAR_1}{CLEAR 0x05}{STR_VAR_2}");

const u8 gText_ShopBuy[] = _("사러 왔다");
const u8 gText_ShopSell[] = _("팔러 왔다");
const u8 gText_ShopQuit[] = _("아무것도 아닙니다");
const u8 gText_ThatItemIsSoldOut[] = _("그 상품은 품절되었습니다{PAUSE_UNTIL_PRESS}");
const u8 gText_SoldOut[] = _("Sold Out");
const u8 gText_InBagVar1[] = _("지닌 개수: {STR_VAR_1}");
const u8 gText_QuitShopping[] = _("쇼핑을 그만둡니다");
const u8 gText_Var1CertainlyHowMany[] = _("{STR_VAR_1}{K_EULREUL}\n몇 개 구입하시겠습니까?");
const u8 gText_Var1CertainlyHowMany2[] = _("{STR_VAR_1}{K_EULREUL}\n몇 개 구입하시겠습니까?");
const u8 gText_Var1AndYouWantedVar2[] = _("{STR_VAR_1} {STR_VAR_2}개로군요\n총 {STR_VAR_3}원입니다");
const u8 gText_Var1AndYouWantedVar2BP[] = _("{STR_VAR_1} {STR_VAR_2}개로군요\n총 {STR_VAR_3}BP입니다");
const u8 gText_Var1IsItThatllBeVar2[] = _("{STR_VAR_1} 말이죠!\n{STR_VAR_2}원인데 사실래요?");
const u8 gText_YouWantedVar1ThatllBeVar2[] = _("{STR_VAR_1} 말이죠!\n{STR_VAR_2}원인데 사실래요?");
const u8 gText_YouWantedVar1ThatllBeVar2BP[] = _("{STR_VAR_1} 말이죠!\n{STR_VAR_2}BP인데 사실래요?");
const u8 gText_HereYouGoThankYou[] = _("네 여기 있습니다\n대단히 감사합니다");
const u8 gText_ThankYouIllSendItHome[] = _("감사합니다!\n집의 PC로 전송해 드리겠습니다");
const u8 gText_ThanksIllSendItHome[] = _("감사합니다!\n집의 PC로 전송해 드리겠습니다");
const u8 gText_YouDontHaveMoney[] = _("돈이 부족하시군요!{PAUSE_UNTIL_PRESS}");
const u8 gText_YouDontHaveEnoughBP[] = _("BP가 부족하시군요!{PAUSE_UNTIL_PRESS}");
const u8 gText_DontHaveEnoughVar1[] = _("{STR_VAR_1}{K_IGA} 부족하시군요!{PAUSE_UNTIL_PRESS}");
const u8 gText_Var1SureHowMany[] = _("{STR_VAR_1}{K_EULREUL}\n몇 개 구입하시겠습니까?");
const u8 gText_xOne[] = _("x1");
const u8 gText_xFive[] = _("x5");
const u8 gText_KurtVar1AndYouWantedVar2Plural[] = _("{STR_VAR_2}개를 만들어 달라는 거지?\n{STR_VAR_1} {STR_VAR_3}개가 필요하단다");
const u8 gText_KurtVar1AndYouWantedVar2Singular[] = _("{STR_VAR_2}개를 만들어 달라는 거지?\n{STR_VAR_1} {STR_VAR_3}개가 필요하단다");
const u8 gText_KurtGettingStarted[] = _("강집: 지금 바로 만들어주마!");
const u8 gText_ExitMenu[] = _("닫는다");
const u8 gText_NoMoreRoomForThis[] = _("그 이상은\n가지고 다닐 수 없어요!{PAUSE_UNTIL_PRESS}");
const u8 gText_SpaceForVar1Full[] = _("{STR_VAR_1}{K_EUNNEUN}\n그 이상 지닐 수 없습니다!{PAUSE_UNTIL_PRESS}");
const u8 gText_AnythingElseICanHelp[] = _("그 밖에 저희가\n뭐 도와드릴 건 없습니까?");
const u8 gText_CanIHelpWithAnythingElse[] = _("그 밖에 뭔가 필요한가요?");
const u8 gText_ThrowInPremierBall[] = _("프레미어볼 1개를\n서비스로 드리겠습니다!{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowInPremierBalls[] = _("프레미어볼 {STR_VAR_1}개를\n서비스로 드리겠습니다!{PAUSE_UNTIL_PRESS}");
const u8 gText_CantBuyKeyItem[] = _("{STR_VAR_2}{K_EUNNEUN}\n파실 수 없습니다!{PAUSE_UNTIL_PRESS}");
const u8 gText_HowManyToSell[] = _("{STR_VAR_2}{K_EULREUL}\n몇 개 파시겠습니까?");
const u8 gText_ICanPayVar1[] = _("그 물건은 {STR_VAR_1}원으로\n쳐 드리겠습니다");
const u8 gText_TurnedOverVar1ForVar2[] = _("{STR_VAR_2}{K_EULREUL} 건네고\n{STR_VAR_1}원을 받았다");
const u8 gText_PokedollarVar1[] = _("{STR_VAR_1}원");
const u8 gText_HP3[] = _("체력");
const u8 gText_SpAtk3[] = _("특수공격");
const u8 gText_SpDef3[] = _("특수방어");
const u8 gText_WontHaveEffect[] = _("써도 효과가 없다!{PAUSE_UNTIL_PRESS}");
const u8 gText_NextFusionMon[] = _("어느 포켓몬과\n합체하겠습니까?");
const u8 gText_CantBeUsedOnPkmn[] = _("그 포켓몬에게는\n쓸 수 없습니다{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCantSwitchOut[] = _("{STR_VAR_1}{K_EULREUL}\n돌아오게 할 수 없습니다!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyInBattle[] = _("{STR_VAR_1}{K_EUNNEUN}\n이미 배틀에 나가 있습니다{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadySelected[] = _("{STR_VAR_1}{K_EUNNEUN} 이미\n선택되어 있습니다{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHasNoEnergy[] = _("{STR_VAR_1}{K_EUNNEUN} 싸우기 위한\n기력이 남아있지 않습니다!{PAUSE_UNTIL_PRESS}");
const u8 gText_CantSwitchWithAlly[] = _("{STR_VAR_1}의 포켓몬과는\n교체할 수 없습니다!{PAUSE_UNTIL_PRESS}");
const u8 gText_EggCantBattle[] = _("알은\n배틀에 내보낼 수 없습니다{PAUSE_UNTIL_PRESS}");
const u8 gText_CantUseUntilNewBadge[] = _("새로운 배지를 얻을 때까지\n아직 쓸 수 없습니다{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMoreThanVar1Pkmn[] = _("참가할 수 있는 포켓몬은\n{STR_VAR_1}마리까지입니다!{PAUSE_UNTIL_PRESS}");
const u8 gText_SendMailToPC[] = _("받은 메일을 PC로\n전송하겠습니까?");
const u8 gText_MailSentToPC[] = _("메일을 PC에\n전송하였습니다{PAUSE_UNTIL_PRESS}");
const u8 gText_PCMailboxFull[] = _("PC의 메일박스가\n가득 찼습니다!{PAUSE_UNTIL_PRESS}");
const u8 gText_MailMessageWillBeLost[] = _("메일을 받으면 메시지가 지워집니다\n괜찮겠습니까?");
const u8 gText_RemoveMailBeforeItem[] = _("메일이 있으면\n도구를 지닐 수 없습니다!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWasGivenItem[] = _("{STR_VAR_1}에게\n{STR_VAR_2}{K_EULREUL} 지니게 했다!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyHoldingItemSwitch[] = _("{STR_VAR_1}{K_EUNNEUN} 이미\n{STR_VAR_2}{K_EULREUL} 지니고 있습니다\p지니고 있는 도구를\n교환하겠습니까?");
const u8 gText_PkmnNotHolding[] = _("{STR_VAR_1}{K_EUNNEUN} 도구를 아무것도\n지니고 있지 않습니다!{PAUSE_UNTIL_PRESS}");
const u8 gText_ReceivedItemFromPkmn[] = _("{STR_VAR_1}{K_EU}로부터\n{STR_VAR_2}{K_EULREUL} 가져왔습니다!{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTakenFromPkmn[] = _("포켓몬으로부터 메일을\n받았습니다!{PAUSE_UNTIL_PRESS}");
const u8 gText_SwitchedPkmnItem[] = _("{STR_VAR_2}{K_EULREUL} 가져오고\n{STR_VAR_1}{K_EULREUL} 지니게 했습니다!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHoldingItemCantHoldMail[] = _("이미 도구를 지니고 있으므로\n메일을 지니게 할 수 없습니다{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTransferredFromMailbox[] = _("박스에서 메일을 옮겼습니다{PAUSE_UNTIL_PRESS}");
const u8 gText_BagFullCouldNotRemoveItem[] = _("가방이 가득 차서 포켓몬의\n도구를 받을 수 없습니다!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnLearnedMove3[] = _("{STR_VAR_1}{K_EUNNEUN} 새로\n{STR_VAR_2}{K_EULREUL} 배웠다!");
const u8 gText_PkmnLearnedMove4[] = _("{STR_VAR_1}{K_EUNNEUN} 새로\n{STR_VAR_2}{K_EULREUL} 배웠다!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCantLearnMove[] = _("{STR_VAR_1}{K_WAGWA} {STR_VAR_2}{K_EUNNEUN}\n상성이 좋지 않았다!\p{STR_VAR_2}{K_EUNNEUN} 배울 수 없다!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnNeedsToReplaceMove[] = _("{STR_VAR_1}{K_EUNNEUN} 새로\n{STR_VAR_2}{K_EULREUL} 배우고 싶다...!\p그러나 {STR_VAR_1}{K_EUNNEUN} 기술을 4개\n알고 있으므로 더 이상 배울 수 없다!\p{STR_VAR_2} 대신\n다른 기술을 잊게 하겠습니까?");
const u8 gText_StopLearningMove2[] = _("그럼... {STR_VAR_2}{K_EULREUL}\n배우는 것을 포기하겠습니까?");
const u8 gText_MoveNotLearned[] = _("{STR_VAR_1}{K_EUNNEUN} {STR_VAR_2}{K_EULREUL}\n결국 배우지 않았다!{PAUSE_UNTIL_PRESS}");
const u8 gText_WhichMoveToForget[] = _("어느 기술을 잊게 하겠습니까?{PAUSE_UNTIL_PRESS}");
const u8 gText_12PoofForgotMove[] = _("{PAUSE 32}1, {PAUSE 15}2, {PAUSE 15}... {PAUSE 15}... {PAUSE 15}... {PLAY_SE 0x0038}짠!\p{STR_VAR_1}{K_EUNNEUN} {STR_VAR_2}{K_EULREUL}\n깨끗이 잊었다!\p그리고...!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyKnows[] = _("{STR_VAR_1}{K_EUNNEUN} 이미\n{STR_VAR_2}{K_EULREUL} 기억하고 있습니다{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHPRestoredByVar2[] = _("{STR_VAR_1}의 체력이\n{STR_VAR_2} 회복되었다!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfPoison[] = _("{STR_VAR_1}의 독은\n말끔하게 해독됐다!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfParalysis[] = _("{STR_VAR_1}의\n몸저림이 풀렸다!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWokeUp2[] = _("{STR_VAR_1}{K_EUNNEUN}\n눈을 떴다!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnBurnHealed[] = _("{STR_VAR_1}의\n화상이 나았다!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFrostbiteHealed[] = _("{STR_VAR_1}의\n동상이 나았다!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnThawedOut[] = _("{STR_VAR_1}의\n얼었던 몸이 녹았다!{PAUSE_UNTIL_PRESS}");
const u8 gText_PPWasRestored[] = _("기술포인트를 회복했다!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnRegainhedHealth[] = _("{STR_VAR_1}{K_EUNNEUN}\n기력을 회복했다!{PAUSE_UNTIL_PRESS}"); // Unused
const u8 gText_PkmnBecameHealthy[] = _("{STR_VAR_1}{K_EUNNEUN}\n건강해졌다!{PAUSE_UNTIL_PRESS}");
const u8 gText_MovesPPIncreased[] = _("{STR_VAR_1}의\n기술포인트가 늘었다!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnElevatedToLvVar2[] = _("{STR_VAR_1}{K_EUNNEUN}\n레벨{STR_VAR_2}{K_EU}로 올랐다!");
const u8 gText_PkmnGainedExp[] = _("{STR_VAR_1}{K_EUNNEUN}\n{STR_VAR_2} 경험치를 얻었다!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGainedExpAndElevatedToLvVar3[] = _("{STR_VAR_1}{K_EUNNEUN}\n{STR_VAR_2} 경험치를 얻고\l레벨{STR_VAR_3}{K_EU}로 올랐다!");
const u8 gText_PkmnBaseVar2StatIncreased[] = _("{STR_VAR_1}{K_EUNNEUN} {STR_VAR_2}의\n기초포인트가 올라갔다!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFriendlyBaseVar2Fell[] = _("{STR_VAR_1}{K_WAGWA} 조금 친해졌다!\n{STR_VAR_2}의 기초포인트가 떨어졌다!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAdoresBaseVar2Fell[] = _("{STR_VAR_1}{K_WAGWA} 최고로 친한 상태다!\n{STR_VAR_2}의 기초포인트가 떨어졌다!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFriendlyBaseVar2CantFall[] = _("{STR_VAR_1}{K_WAGWA} 조금 친해졌다!\n{STR_VAR_2}의 기초포인트는 더 떨어지지 않는다!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnSnappedOutOfConfusion[] = _("{STR_VAR_1}의\n혼란이 풀렸다!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGotOverInfatuation[] = _("{STR_VAR_1}의\n헤롱헤롱이 풀렸다!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnTransformed[] = _("{STR_VAR_1}의\n모습이 변화했다!{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowAwayItem[] = _("{STR_VAR_1}{K_EULREUL}\n버려도 괜찮겠습니까?");
const u8 gText_ItemThrownAway[] = _("{STR_VAR_1}{K_EULREUL}\n버렸습니다{PAUSE_UNTIL_PRESS}");
const u8 gText_TeachWhichPokemon2[] = _("어느 포켓몬에게 가르칠까?"); // Unused
const u8 gText_ChoosePokemon[] = _("포켓몬을 선택해 주십시오");
const u8 gText_MoveToWhere[] = _("어느 포켓몬과 바꿀까?");
const u8 gText_TeachWhichPokemon[] = _("어느 포켓몬에게 가르칠까?");
const u8 gText_UseOnWhichPokemon[] = _("어느 포켓몬에게 사용할까?");
const u8 gText_GiveToWhichPokemon[] = _("어느 포켓몬에게 건네줄까?");
const u8 gText_DoWhatWithPokemon[] = _("{STR_VAR_1}{K_EULREUL} 어떻게 할까?");
const u8 gText_NothingToCut[] = _("벨 수 있는 것이 없습니다!");
const u8 gText_CantSurfHere[] = _("여기서는 탈 수 없습니다");
const u8 gText_AlreadySurfing[] = _("이미 파도타기를 하고 있습니다");
const u8 gText_CantUseHere[] = _("여기서는 쓸 수 없습니다");
const u8 gText_RestoreWhichMove[] = _("어느 기술을 회복하겠습니까?");
const u8 gText_BoostPp[] = _("어느 기술의 포인트를 늘릴까?");
const u8 gText_DoWhatWithItem[] = _("지닌물건을 어떻게 할까?");
const u8 gText_NoPokemonForBattle[] = _("대전에 내보낼 포켓몬이 없습니다!");
const u8 gText_ChoosePokemon2[] = _("어느 포켓몬을 맡기겠습니까?");
const u8 gText_NotEnoughHp[] = _("체력이 부족합니다...");
const u8 gText_PokemonAreNeeded[] = _("{STR_VAR_1}마리가 필요합니다");
const u8 gText_PokemonCantBeSame[] = _("같은 포켓몬이 있습니다!");
const u8 gText_NoIdenticalHoldItems[] = _("같은 도구를 지닌 포켓몬이 있습니다");
const u8 gText_CurrentIsTooFast[] = _("해류가 빨라서 갈 수 없다!");
const u8 gText_DoWhatWithMail[] = _("메일을 어떻게 할까?");
const u8 gText_ChoosePokemonCancel[] = _("포켓몬이나 취소를 선택");
const u8 gText_ChoosePokemonConfirm[] = _("포켓몬을 선택하고 결정");
const u8 gText_SendWhichMonToPC[] = _("포켓몬을 선택해 주십시오");
const u8 gText_MoveItemWhere[] = _("어느 포켓몬과 교체할까?");
const u8 gText_XsYAnd[] = _("{STR_VAR_1}의 {STR_VAR_2}와\n");
const u8 gText_XsYWereSwapped[] = _("{STR_VAR_1}의 {STR_VAR_2}{K_IGA} 교체되었다!{PAUSE_UNTIL_PRESS}");
const u8 gText_EnjoyCycling[] = _("사이클링을 즐겨보자!");
const u8 gText_InUseAlready_PM[] = _("이미 사용하고 있습니다!");
const u8 gText_AlreadyHoldingOne[] = _("{STR_VAR_1}{K_EUNNEUN}\n{STR_VAR_2}{K_EULREUL} 지니고 있습니다");
const u8 gText_WhichAppliance[] = _("어느 가전제품을\n주문하겠습니까?");
const u8 gText_NoUse[] = _("쓸 수 없습니다");
const u8 gText_Able[] = _("참가 안 한다");
const u8 gText_First_PM[] = _("첫 번째");
const u8 gText_Second_PM[] = _("두 번째");
const u8 gText_Third_PM[] = _("세 번째");
const u8 gText_Able2[] = _("나갈 수 있어요");
const u8 gText_NotAble[] = _("나갈 수 없어요");
const u8 gText_Able3[] = _("배울 수 있다!");
const u8 gText_NotAble2[] = _("배울 수 없다");
const u8 gText_Learned[] = _("이미 알고 있다");
const u8 gText_Have[] = _("지니고 있다");
const u8 gText_DontHave[] = _("지니고 있지 않다");
const u8 gText_Fourth[] = _("네 번째");
const u8 gText_PkmnCantParticipate[] = _("그 포켓몬은 참가할 수 없습니다{PAUSE_UNTIL_PRESS}");
const u8 gText_CancelParticipation[] = _("참가를 그만두겠습니까?");
const u8 gText_CancelBattle[] = _("대전을 중지할까요?");
const u8 gText_ReturnToWaitingRoom[] = _("대기실로 되돌아갈까요?");
const u8 gText_CancelChallenge[] = _("도전을 중지할까요?");
const u8 gText_EscapeFromHere[] = _("여기서 탈출해서\n{STR_VAR_1}{K_EU}로 되돌아갈까요?");
const u8 gText_ReturnToHealingSpot[] = _("마지막으로 휴식을 취한\n{STR_VAR_1}{K_EU}로 순간이동할까요?");
const u8 gText_PauseUntilPress[] = _("{PAUSE_UNTIL_PRESS}");
const u8 gJPText_AreYouSureYouWantToSpinTradeMon[] = _("{STR_VAR_1}{K_EULREUL} 빙글빙글 교환에\n내보내도 괜찮겠습니까?");
ALIGNED(4) const u8 gText_OnlyPkmnForBattle[] = _("그 포켓몬을 교환하면\n싸울 수 없게 됩니다!");
ALIGNED(4) const u8 gText_PkmnCantBeTradedNow[] = _("그 포켓몬은 지금\n교환할 수 없습니다");
ALIGNED(4) const u8 gText_PkmnCantBeTraded[] = _("그 포켓몬은\n교환할 수 없습니다");
ALIGNED(4) const u8 gText_EggCantBeTradedNow[] = _("알은 지금\n교환에 내보낼 수 없습니다");
ALIGNED(4) const u8 gText_OtherTrainersPkmnCantBeTraded[] = _("상대의 포켓몬과는\n지금 교환할 수 없습니다");
ALIGNED(4) const u8 gText_OtherTrainerCantAcceptPkmn[] = _("상대는 지금 그 포켓몬을\n받을 수 없습니다");
ALIGNED(4) const u8 gText_CantTradeWithTrainer[] = _("그 상대와 지금은\n교환할 수 없습니다");
ALIGNED(4) const u8 gText_NotPkmnOtherTrainerWants[] = _("상대가 갖고 싶어하는 타입의\n포켓몬이 아닙니다");
ALIGNED(4) const u8 gText_ThatIsntAnEgg[] = _("그것은 알이 아닙니다");
const u8 gText_Register[] = _("등록한다");
const u8 gText_Attack3[] = _("공격");
const u8 gText_Defense3[] = _("방어");
const u8 gText_SpAtk4[] = _("특수공격");
const u8 gText_SpDef4[] = _("특수방어");
const u8 gText_Speed2[] = _("스피드");
const u8 gText_HP4[] = _("HP");
const u8 gText_EmptyString8[] = _(""); // Unused
const u8 gText_OTSlash[] = _("어버이/");
const u8 gText_RentalPkmn[] = _("대여 포켓몬");
const u8 gText_TypeSlash[] = _("타입/");
const u8 gText_Power[] = _("위력");
const u8 gText_Accuracy2[] = _("명중");
const u8 gText_Appeal[] = _("어필");
const u8 gText_Jam[] = _("방해");
const u8 gText_Status[] = _("상태");
const u8 gText_ExpPoints[] = _("현재 경험치");
const u8 gText_NextLv[] = _("다음 레벨까지");
const u8 gText_RibbonsVar1[] = _("{STR_VAR_1}개");
const u8 gText_EmptyString5[] = _("");
const u8 gText_Events[] = _("이벤트"); // Unused
const u8 gText_Switch[] = _("교체");
const u8 gText_PkmnInfo[] = _("포켓몬 정보");
const u8 gText_PkmnSkills[] = _("포켓몬 능력");
const u8 gText_BattleMoves[] = _("싸울 기술");
const u8 gText_ContestMoves[] = _("콘테스트 기술");
const u8 gText_Info[] = _("자세히");
const u8 gText_EggWillTakeALongTime[] = _("이 알은 태어나기까지 상당한\n시간이 걸릴 것 같다");
const u8 gText_EggWillTakeSomeTime[] = _("무엇이 태어날까? 태어나기까지\n아직 시간이 걸릴 것 같다");
const u8 gText_EggWillHatchSoon[] = _("가끔 움직이고 있는 것 같다\n태어나기까지 이제 조금 남은 건가?");
const u8 gText_EggAboutToHatch[] = _("안에서 소리가 들려온다\n이제 곧 태어날 것 같아!");
const u8 gText_EggReadyToHatch_Nuzlocke[] = _("너즐록 조우 제한 때문에\n태어날 수 없는 상태다!");
const u8 gText_HMMovesCantBeForgotten2[] = _("중요한 기술입니다\n잊게 할 수 없습니다!");
const u8 gText_XNatureMetAtYZ[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} 성격.\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}\n에서 {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}일 때 만났다.");
const u8 gText_XNatureHatchedAtYZ[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} 성격.\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}\n에서 부화하여 만났다.");
const u8 gText_XNatureObtainedInTrade[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} 성격.\n통신교환\n에서 {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}일 때 왔다.");
const u8 gText_XNatureFatefulEncounter[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} 성격.\n{LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}일 때\n운명적인 만남을 가진 것 같다");
const u8 gText_XNatureProbablyMetAt[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} 성격.\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}\n에서 {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}일 때 만난 것 같다");
const u8 gText_XNature[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} 성격.");
const u8 gText_XNatureMetSomewhereAt[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} 성격.\n{DYNAMIC 0}어딘가{DYNAMIC 1}\n에서 {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}일 때 만났다.");
const u8 gText_XNatureHatchedSomewhereAt[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} 성격.\n{DYNAMIC 0}어딘가{DYNAMIC 1}\n에서 부화하여 만났다.");
const u8 gText_OddEggFoundByCouple[] = _("키우미집 부부에게서 받은\n이상한 포켓몬알이다");
const u8 gText_PeculiarEggNicePlace[] = _("근사한 장소에서 손에 넣은\n이상하고 또 이상한 포켓몬알이다");
const u8 gText_PeculiarEggTrade[] = _("통신교환으로 손에 넣은\n이상한 포켓몬알이다");
const u8 gText_EggFromHotSprings[] = _("온천할머니에게서 받은\n이상한 포켓몬알이다");
const u8 gText_OddEggFromDaycare[] = _("키우미집에서 받은\n이상한 포켓몬알이다");
const u8 gText_EggFromTraveler[] = _("나그네 아저씨에게서 받은\n이상한 포켓몬알이다");
const u8 gText_ApostropheSBase[] = _("의 비밀기지");
const u8 gText_OkayToDeleteFromRegistry[] = _("{STR_VAR_1}의 등록을\n해제해도 괜찮겠습니까?");
const u8 gText_RegisteredDataDeleted[] = _("등록을 해제했습니다{PAUSE_UNTIL_PRESS}");
const u8 gText_NoRegistry[] = _("등록 리스트가 없습니다{PAUSE_UNTIL_PRESS}");
const u8 gText_DelRegist[] = _("등록 해제");
const u8 gText_Var3Var1SlashVar2[] = _("{STR_VAR_3}{STR_VAR_1}/{STR_VAR_2}"); // Unused
const u8 gText_Decorate[] = _("굿즈를 꺼낸다");
const u8 gText_PutAway[] = _("굿즈를 되돌린다");
const u8 gText_Toss2[] = _("굿즈를 버린다");
const u8 gText_Color161Shadow161[] = _("{COLOR 161}{SHADOW 161}");
const u8 gText_PutOutSelectedDecorItem[] = _("선택한 굿즈를 방으로 꺼냅니다!");
const u8 gText_StoreChosenDecorInPC[] = _("선택한 굿즈를 PC로 되돌립니다!");
const u8 gText_ThrowAwayUnwantedDecors[] = _("필요 없어진 굿즈를 버립니다!");
const u8 gText_NoDecorations[] = _("굿즈가 없습니다!{PAUSE_UNTIL_PRESS}");
const u8 gText_Desk[] = _("책상");
const u8 gText_Chair[] = _("의자");
const u8 gText_Plant[] = _("화분");
const u8 gText_Ornament[] = _("장식품");
const u8 gText_Mat[] = _("매트");
const u8 gText_Poster[] = _("벽장식");
const u8 gText_Doll[] = _("봉제인형");
const u8 gText_Cushion[] = _("쿠션");
const u8 gText_Gold[] = _("골드");
const u8 gText_Silver[] = _("실버");
const u8 gText_PlaceItHere[] = _("여기에 놓겠습니까?");
const u8 gText_CantBePlacedHere[] = _("여기에 놓을 수 없습니다!");
const u8 gText_CancelDecorating[] = _("놓기를 그만두겠습니까?");
const u8 gText_InUseAlready[] = _("이미 놓여 있습니다!");
const u8 gText_NoMoreDecorations[] = _("더는 놓을 수 없습니다\n비밀기지에 놓는 건{STR_VAR_1}개까지입니다");
const u8 gText_NoMoreDecorations2[] = _("더는 놓을 수 없습니다\n방에 놓는 건{STR_VAR_1}개까지입니다");
const u8 gText_MustBePlacedOnDesk[] = _("여기에 놓을 수 없습니다!\n책상 위 등에 놓아 주십시오!"); // Unused
const u8 gText_CantPlaceInRoom[] = _("이 굿즈는\n자신의 방에 놓을 수 없습니다!");
const u8 gText_CantThrowAwayInUse[] = _("이 굿즈는 놓여 있으므로\n버릴 수 없습니다!");
const u8 gText_DecorationWillBeDiscarded[] = _("{STR_VAR_1}{K_IGA} 없어져 버립니다만\n괜찮겠습니까?");
const u8 gText_DecorationThrownAway[] = _("굿즈를 버렸습니다!");
const u8 gText_StopPuttingAwayDecorations[] = _("되돌리는 것을 그만두겠습니까?");
const u8 gText_NoDecorationHere[] = _("여기에는 굿즈가 없습니다!");
const u8 gText_ReturnDecorationToPC[] = _("이 굿즈를 PC로 되돌리겠습니까?");
const u8 gText_DecorationReturnedToPC[] = _("굿즈를 PC로 되돌렸습니다!");
const u8 gText_NoDecorationsInUse[] = _("굿즈가 놓여 있지 않습니다!{PAUSE_UNTIL_PRESS}");
const u8 gText_NoItems[] = _("아무것도 없습니다!{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMailHere[] = _("메일이 1통도 없습니다{PAUSE_UNTIL_PRESS}");
const u8 gText_WhatToDoWithVar1sMail[] = _("{STR_VAR_1}의\n메일을 어떻게 하겠습니까?");
const u8 gText_MessageWillBeLost[] = _("내용은 사라져 버립니다만\n괜찮겠습니까?");
const u8 gText_BagIsFull[] = _("가방이 가득 찼습니다!{PAUSE_UNTIL_PRESS}");
const u8 gText_MailToBagMessageErased[] = _("내용을 지운 메일을\n가방에 넣었습니다{PAUSE_UNTIL_PRESS}");
const u8 gText_Dad[] = _("아빠");
const u8 gText_Mom[] = _("엄마");
const u8 gText_MomHowMuchDeposit[] = _("엄마에게 돈을 얼마나\n맡기겠습니까?");
const u8 gText_MomHowMuchWithdraw[] = _("엄마에게 맡긴 돈을\n얼마나 찾겠습니까?");
const u8 gText_MomMatchCallDesc[] = _("");
const u8 gText_MomMatchCallName[] = _("엄마");
const u8 gText_MomMenuCheckSavings[] = _("맡긴 금액 확인");
const u8 gText_MomMenuDeposit[] = _("맡긴다");
const u8 gText_MomMenuWithdraw[] = _("찾는다");
const u8 gText_MomMenuToggleSaving[] = _("변경");
const u8 gText_MomMenuExit[] = _("그만둔다");
const u8 gText_Info2[] = _("설명을 듣는다");
const u8 gText_CoolnessContest[] = _("근사함콘테스트");
const u8 gText_BeautyContest[] = _("아름다움콘테스트");
const u8 gText_CutenessContest[] = _("귀여움콘테스트");
const u8 gText_SmartnessContest[] = _("슬기로움콘테스트");
const u8 gText_ToughnessContest[] = _("강인함콘테스트");
const u8 gText_Decoration2[] = _("모양바꾸기");
const u8 gText_PackUp[] = _("이사");
const u8 gText_Count[] = _("카운트"); //unused
const u8 gText_Registry[] = _("등록 리스트");
const u8 gText_Information[] = _("등록 설명");
const u8 gText_Yes[] = _("예");
const u8 gText_No[] = _("아니오");
const u8 gText_Lv50[] = _("LV. 50");
const u8 gText_OpenLevel[] = _("오픈 레벨");
const u8 gText_RedShard[] = _("빨강조각");
const u8 gText_YellowShard[] = _("노랑조각");
const u8 gText_BlueShard[] = _("파랑조각");
const u8 gText_GreenShard[] = _("초록조각");
const u8 gText_BattleFrontier[] = _("배틀프런티어");
const u8 gText_Cool[] = _("근사함");
const u8 gText_Beauty[] = _("아름다움");
const u8 gText_Cute[] = _("귀여움");
const u8 gText_Smart[] = _("슬기로움");
const u8 gText_Tough[] = _("강인함");
const u8 gText_Normal[] = _("노말");
const u8 gText_Super[] = _("슈퍼");
const u8 gText_Hyper[] = _("하이퍼");
const u8 gText_Master[] = _("마스터");
const u8 gText_Cool2[] = _("근사함");
const u8 gText_Beauty2[] = _("아름다움");
const u8 gText_Cute2[] = _("귀여움");
const u8 gText_Smart2[] = _("슬기로움");
const u8 gText_Tough2[] = _("강인함");
const u8 gText_Items[] = _("도구");
const u8 gText_Key_Items[] = _("중요한 물건");
const u8 gText_Poke_Balls[] = _("몬스터볼");
const u8 gText_TMs_Hms[] = _("기술머신");
const u8 gText_Berries2[] = _("나무열매");
const u8 gText_Medicine[] = _("회복");
#if I_COMBINE_BAG_POCKETS == FALSE
const u8 gText_BattleItems[] = _("배틀");
const u8 gText_Treasures[] = _("보물");
#endif
const u8 gText_SomeonesPC[] = _("누군가의 PC");
const u8 gText_LanettesPC[] = _("유미의 PC");
const u8 gText_BillsPc[] = _("이수재 PC");
const u8 gText_PlayersPC[] = _("{PLAYER}의 PC");
const u8 gText_HallOfFame[] = _("전당등록");
const u8 gText_LogOff[] = _("스위치를 끈다");
const u8 gText_Challenges[] = _("챌린지 설정");
const u8 gText_Opponent[] = _("대전 상대");
const u8 gText_Tourney_Tree[] = _("토너먼트 표");
const u8 gText_ReadyToStart[] = _("준비 완료");
const u8 gText_Single2[] = _("싱글");
const u8 gText_Double2[] = _("더블");
const u8 gText_Multi[] = _("멀티");
const u8 gText_MultiLink[] = _("통신 멀티");
const u8 gText_MenuOptionPokedex[] = _("도감");
const u8 gText_MenuOptionPokemon[] = _("포켓몬");
const u8 gText_MenuOptionBag[] = _("가방");
#if IS_HNS
const u8 gText_MenuOptionPokenav[] = _("포켓기어");
#else
const u8 gText_MenuOptionPokenav[] = _("포켓내비");
#endif
const u8 gText_Blank[] = _("");
const u8 gText_MenuOptionSave[] = _("리포트");
const u8 gText_MenuOptionOption[] = _("설정");
const u8 gText_MenuOptionExit[] = _("닫는다");
const u8 gText_SouthernIsland[] = _("남쪽의 외딴섬");
const u8 gText_BirthIsland[] = _("탄생의 섬");
const u8 gText_FarawayIsland[] = _("머나먼 고도");
const u8 gText_NavelRock[] = _("배꼽바위");
const u8 gText_NormalTagMatch[] = _("노말 태그매치");
const u8 gText_VarietyTagMatch[] = _("슈퍼 태그매치");
const u8 gText_UniqueTagMatch[] = _("하이퍼 태그매치");
const u8 gText_ExpertTagMatch[] = _("마스터 태그매치");
const u8 gText_TradeCenter[] = _("트레이드센터");
const u8 gText_Colosseum[] = _("콜로세움");
const u8 gText_RecordCorner[] = _("레코드코너");
const u8 gText_BerryCrush3[] = _("나무열매크러시");
const u8 gText_BattleRules[] = _("배틀에서의 주의");
const u8 gText_JudgeMind[] = _("판정 “마음”");
const u8 gText_JudgeSkill[] = _("판정 “기술”");
const u8 gText_JudgeBody[] = _("판정 “몸”");
const u8 gText_BasicRules[] = _("기본 룰");
const u8 gText_SwapPartners[] = _("트레이드 상대");
const u8 gText_SwapNumber[] = _("트레이드 횟수");
const u8 gText_SwapNotes[] = _("트레이드 주의");
const u8 gText_BattleBasics[] = _("배틀의 기본");
const u8 gText_PokemonNature[] = _("포켓몬의 성격");
const u8 gText_PokemonMoves[] = _("포켓몬의 기술");
const u8 gText_Underpowered[] = _("힘을 발휘할 수 없다");
const u8 gText_WhenInDanger[] = _("위급할 때");
const u8 gText_BattlePokemon[] = _("나와있는 포켓몬");
const u8 gText_BattleTrainers[] = _("배틀하는 트레이너");
const u8 gText_GoOn[] = _("계속한다");
const u8 gText_Record2[] = _("기록한다");
const u8 gText_Rest[] = _("쉰다");
const u8 gText_Retire[] = _("포기한다");
const u8 gText_1F[] = _("1층");
const u8 gText_2F[] = _("2층");
const u8 gText_3F[] = _("3층");
const u8 gText_4F[] = _("4층");
const u8 gText_5F[] = _("5층");
const u8 gText_6F[] = _("6층");
const u8 gText_7F[] = _("7층");
const u8 gText_8F[] = _("8층");
const u8 gText_9F[] = _("9층");
const u8 gText_10F[] = _("10층");
const u8 gText_11F[] = _("11층");
const u8 gText_B1F[] = _("지하1층");
const u8 gText_B2F[] = _("지하2층");
const u8 gText_B3F[] = _("지하3층");
const u8 gText_B4F[] = _("지하4층");
const u8 gText_Rooftop[] = _("옥상");
const u8 gText_ElevatorNowOn[] = _("현재 플로어");
const u8 gText_BP[] = _("BP");
const u8 gText_RankingHall[] = _("랭킹홀");
const u8 gText_ExchangeService[] = _("교환 서비스");
const u8 gText_LilycoveCity[] = _("해안시티");
const u8 gText_SlateportCity[] = _("잿빛도시");
const u8 gText_Exit[] = _("그만둔다");
const u8 gText_YourPartysFull[] = _("지닌 포켓몬이 가득합니다!");
const u8 gText_InParty[] = _("데리고 있음");
const u8 gText_PokemonMaleLv[] = _("{DYNAMIC 0}♂/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonFemaleLv[] = _("{DYNAMIC 0}♀/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonNoGenderLv[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonMaleLv2[] = _("{DYNAMIC 0}♂/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonFemaleLv2[] = _("{DYNAMIC 0}♀/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonNoGenderLv2[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_CombineFourWordsOrPhrases[] = _("4개의 단어를 조합해서");
const u8 gText_AndMakeYourProfile[] = _("프로필을 만들자!");
const u8 gText_CombineSixWordsOrPhrases[] = _("6개의 단어로 메시지를 만들자!");
const u8 gText_AndMakeAMessage[] = _("");
const u8 gText_FindWordsThatDescribeYour[] = _("지금의 기분에 딱 맞는");
const u8 gText_FeelingsRightNow[] = _("단어를 찾아보자!");
const u8 gText_WithFourPhrases[] = _("4개의 단어로"); // Unused
const u8 gText_CombineNineWordsOrPhrases[] = _("9개의 단어를 조합해서");
const u8 gText_AndMakeAMessage2[] = _("메시지를 만들자!");
const u8 gText_ChangeJustOneWordOrPhrase[] = _("단어를 1개만 바꿔서");
const u8 gText_AndImproveTheBardsSong[] = _("아저씨의 노래를 좋게 해보자!");
const u8 gText_YourProfile[] = _("프로필은");
const u8 gText_YourFeelingAtTheBattlesStart[] = _("대전이 시작될 때의 기분은");
const u8 gText_WhatYouSayIfYouWin[] = _("대전에서 이겼을 때의 인사말은");
const u8 gText_WhatYouSayIfYouLose[] = _("대전에서 졌을 때의 인사말은");
const u8 gText_TheAnswer[] = _("대답은");
const u8 gText_TheMailMessage[] = _("메일에 적을 내용은");
const u8 gText_TheMailSalutation[] = _("메모에 적을 인사말은"); // Unused
const u8 gText_TheBardsSong2[] = _("새로운 노래는");
const u8 gText_CombineTwoWordsOrPhrases[] = _("2개의 단어를 조합해서");
const u8 gText_AndMakeATrendySaying[] = _("유행시키고 싶은 말을 만들자!");
const u8 gText_TheTrendySaying[] = _("유행시키고 싶은 말은");
const u8 gText_IsAsShownOkay[] = _("이 대답으로 하시겠습니까?");
const u8 gText_CombineTwoWordsOrPhrases2[] = _("2개의 단어를 조합해서");
const u8 gText_ToTeachHerAGoodSaying[] = _("좋은 말을 알려주자!");
const u8 gText_FindWordsWhichFit[] = _("트레이너의 이미지에");
const u8 gText_TheTrainersImage[] = _("딱 맞는 말을 찾아보자!");
const u8 gText_TheImage[] = _("이미지는");
const u8 gText_OutOfTheListedChoices[] = _("단어 속에서");
const u8 gText_SelectTheAnswerToTheQuiz[] = _("퀴즈의 답을 선택하자!");
const u8 gText_AndCreateAQuiz[] = _("퀴즈를 만들자!");
const u8 gText_PickAWordOrPhraseAnd[] = _("단어 속에서 하나를 골라");
const u8 gText_SetTheQuizAnswer[] = _("퀴즈의 정답을 만들자!");
const u8 gText_TheAnswerColon[] = _("답은");
const u8 gText_TheQuizColon[] = _("퀴즈는"); // Unused
const u8 gText_ApprenticePhrase[] = _("제자의 마무리 대사는");
const u8 gText_QuitEditing[] = _("편집을 그만두겠습니까?");
const u8 gText_StopGivingPkmnMail[] = _("메일 건네주기를 그만두겠습니까?");
const u8 gText_AndFillOutTheQuestionnaire[] = _("숍의 앙케이트에 답하자!");
const u8 gText_LetsReplyToTheInterview[] = _("인터뷰에 답하자!");
const u8 gText_AllTextBeingEditedWill[] = _("편집 중인 단어를");
const u8 gText_BeDeletedThatOkay[] = _("모두 지워도 괜찮겠습니까?");
const u8 gText_QuitEditing2[] = _("편집을 그만두겠습니까?"); // Unused
const u8 gText_EditedTextWillNotBeSaved[] = _("편집한 단어는 저장되지"); // Unused
const u8 gText_IsThatOkay[] = _("되지 않습니다만 괜찮겠습니까?"); // Unused
const u8 gText_PleaseEnterPhraseOrWord[] = _("단어를 넣어 주십시오!"); // Unused
const u8 gText_EntireTextCantBeDeleted[] = _("단어를 모두 지울 수 없습니다!");
const u8 gText_OnlyOnePhrase[] = _("바꿀 수 있는 단어는 1개까지입니다!");
const u8 gText_OriginalSongWillBeUsed[] = _("노래를 원래대로 되돌립니다!");
const u8 gText_ThatsTrendyAlready[] = _("그건 이미 유행하고 있습니다!"); // Unused
const u8 gText_CombineTwoWordsOrPhrases3[] = _("2개의 단어를 조합해 주십시오!");
const u8 gText_QuitGivingInfo[] = _("말을 알려주지 않겠습니까?"); // Unused
const u8 gText_StopGivingPkmnMail2[] = _("메일 건네주기를 그만두겠습니까?"); // Unused
const u8 gText_CreateAQuiz2[] = _("문제를 만들어 주십시오!"); // Unused
const u8 gText_SetTheAnswer[] = _("답을 선택해 주십시오!"); // Unused
const u8 gText_CancelSelection[] = _("원래대로 되돌려도 괜찮겠습니까?"); // Unused
const u8 gText_Profile[] = _("프로필");
const u8 gText_AtTheBattlesStart[] = _("대전이 시작되었을 때");
const u8 gText_UponWinningABattle[] = _("대전에서 이겼을 때");
const u8 gText_UponLosingABattle[] = _("대전에서 졌을 때");
const u8 gText_TheBardsSong[] = _("아저씨의 노래");
const u8 gText_WhatsHipAndHappening[] = _("지금의 유행어");
const u8 gText_Interview[] = _("인터뷰");
const u8 gText_GoodSaying[] = _("좋은 말");
const u8 gText_FansQuestion[] = _("팬의 질문");
const u8 gJPText_WhatIsTheQuizAnswer[] = _("퀴즈의 답은?"); // Unused
const u8 gText_ApprenticesPhrase[] = _("제자의 마무리 대사");
const u8 gText_Questionnaire[] = _("앙케이트");
const u8 gText_YouCannotQuitHere[] = _("여기서는 도중에");
const u8 gText_SectionMustBeCompleted[] = _("그만둘 수 없습니다!");
const u8 gText_F700sQuiz[] = _("{DYNAMIC 0}님의 퀴즈");
const u8 gText_Lady[] = _("아가씨");
const u8 gText_AfterYouHaveReadTheQuiz[] = _("문제를 읽었다면");
const u8 gText_QuestionPressTheAButton[] = _("A 버튼을 눌러 줘!");
const u8 gText_TheQuizAnswerIs[] = _("퀴즈의 답은?");
const u8 gText_LikeToQuitQuiz[] = _("퀴즈 챌린지를");
const u8 gText_ChallengeQuestionMark[] = _("포기하겠습니까?");
const u8 gText_IsThisQuizOK[] = _("퀴즈는 이걸로 괜찮겠습니까?");
const u8 gText_CreateAQuiz[] = _("문제를 만들어 주십시오!");
const u8 gText_SelectTheAnswer[] = _("답을 선택해 주십시오!");
const u8 gText_LyricsCantBeDeleted[] = _("가사를 지울 수 없습니다!");
const u8 gText_PokemonLeague[] = _("포켓몬리그");
const u8 gText_PokemonCenter[] = _("포켓몬센터");
const u8 gText_Coolness[] = _("근사함");
const u8 gText_Beauty3[] = _("아름다움");
const u8 gText_Cuteness[] = _("귀여움");
const u8 gText_Smartness[] = _("슬기로움");
const u8 gText_Toughness[] = _("강인함");
const u8 gText_SaveFailedCheckingBackup[] = _("데이터를 쓸 수 없었습니다\n백업 메모리를 검사합니다...\n잠시 기다려 주십시오\n{COLOR RED}“1분 정도 걸립니다”");
const u8 gText_BackupMemoryDamaged[] = _("백업 기능이 고장났거나\n수명이 다 되었습니다\n기록은 할 수 없지만\n게임은 즐기실 수 있습니다");
const u8 gText_GamePlayCannotBeContinued[] = _("{COLOR RED}“더 이상 모험을 계속할 수 없습니다\n타이틀 화면으로 돌아갑니다...”");
const u8 gText_CheckCompleted[] = _("검사가 종료되었습니다!\n다시 한 번 더 리포트를 작성합니다\n잠시 기다려 주십시오");
const u8 gText_SaveCompleteGameCannotContinue[] = _("리포트 작성이 끝났습니다\n{COLOR RED}“더 이상 모험을 계속할 수 없습니다\n타이틀 화면으로 돌아갑니다...”");
const u8 gText_SaveCompletePressA[] = _("리포트 작성이 끝났습니다\n{COLOR RED}“A 버튼을 눌러 주십시오”");
const u8 gText_Ferry[] = _("연락선");
const u8 gText_SecretBase[] = _("비밀기지");
const u8 gText_Hideout[] = _("아지트");
const u8 gText_ResetRTCConfirmCancel[] = _("RTC를 리셋합니다\nA 버튼: 결정  B 버튼: 취소");
const u8 gText_PresentTime[] = _("현재 게임 내 시간");
const u8 gText_PreviousTime[] = _("지난번 게임 내 시간");
const u8 gText_PleaseResetTime[] = _("시간을 재설정해 주십시오");
const u8 gText_ClockHasBeenReset[] = _("시간을 재설정했습니다\n리포트 작성까지 기다려 주십시오");
const u8 gText_SaveCompleted[] = _("리포트를 작성했습니다!");
const u8 gText_SaveFailed[] = _("리포트를 작성하는 데\n실패했습니다...");
const u8 gText_NoSaveFileCantSetTime[] = _("리포트가 없으므로\n시간을 설정할 수 없습니다!");
const u8 gText_InGameClockUsable[] = _("게임 내 시간재생 시스템을\n다시 쓸 수 있게 되었습니다!");
const u8 gText_Spicy2[] = _("매운맛");
const u8 gText_Dry2[] = _("떫은맛");
const u8 gText_Sweet2[] = _("단맛");
const u8 gText_Bitter2[] = _("쓴맛");
const u8 gText_Sour2[] = _("신맛");
const u8 gText_Single[] = _("싱글");
const u8 gText_Double[] = _("더블");
const u8 gText_Knockout[] = _("KNOCKOUT");
const u8 gText_Mixed[] = _("MIXED");
const u8 gText_First[] = _("첫 번째");
const u8 gText_Second[] = _("두 번째");
const u8 gText_Third[] = _("세 번째");
#if OW_POISON_DAMAGE < GEN_4
const u8 gText_PkmnFainted_FldPsn[] = _("{STR_VAR_1}{K_EUNNEUN}\n힘이 다했다\p");
#else
const u8 gText_PkmnFainted_FldPsn[] = _("{STR_VAR_1}{K_EUNNEUN} 어떻게든 독을 견뎠다\n독이 사라졌다!\p");
#endif
const u8 gText_PkmnSurvived_FldPsn[] = _("{STR_VAR_1}{K_EUNNEUN} 어떻게든 독을 견뎠다\n독이 사라졌다!\p");
const u8 gText_Marco[] = _("하성");
const u8 gText_TrainerCardName[] = _("이름 ");
const u8 gText_TrainerCardIDNo[] = _("IDNo.");
const u8 gText_TrainerCardMoney[] = _("용돈");
const u8 gText_PokeDollar[] = _("원"); // Unused
const u8 gText_TrainerCardPokedex[] = _("포켓몬 도감");
const u8 gText_EmptyString6[] = _("마리");
const u8 gText_Colon2[] = _(":");
const u8 gText_Points[] = _(""); // Unused
const u8 gText_TrainerCardTime[] = _("플레이 시간");
const u8 gJPText_BattlePoints[] = _("게임포인트"); // Unused. Name presumed, translation is Game Points
const u8 gText_Var1sTrainerCard[] = _("{STR_VAR_1}의 트레이너카드");
const u8 gText_HallOfFameDebut[] = _("첫 전당등록  ");
const u8 gText_LinkBattles[] = _("통신대전");
const u8 gText_LinkCableBattles[] = _("케이블대전");
const u8 gText_WinsLosses[] = _("승{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  패{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}");
const u8 gText_PokemonTrades[] = _("포켓몬 통신교환");
const u8 gText_UnionTradesAndBattles[] = _("유니언 대전과 교환");
const u8 gText_BerryCrush[] = _("나무열매크러시");
const u8 gText_WaitingTrainerFinishReading[] = _("상대가 카드를 다 보기를\n기다리고 있습니다");
const u8 gText_PokeblocksWithFriends[] = _("친구와 만든 포켓몬스넥");
const u8 gText_NumPokeblocks[] = _("{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}");
const u8 gText_WonContestsWFriends[] = _("친구와 콘테스트 우승");
const u8 gText_BattlePtsWon[] = _("얻은 배틀포인트");
const u8 gText_NumBP[] = _("{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BP");
const u8 gText_BattleTower[] = _("배틀타워");
const u8 gText_WinsStraight[] = _("승{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  연승{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}");
const u8 gText_BattleTower2[] = _("배틀타워");
const u8 gText_BattleDome[] = _("배틀돔");
const u8 gText_BattlePalace[] = _("배틀팰리스");
const u8 gText_BattleFactory[] = _("배틀팩토리");
const u8 gText_BattleArena[] = _("배틀아레나");
const u8 gText_BattlePike[] = _("배틀튜브");
const u8 gText_BattlePyramid[] = _("배틀피라미드");

ALIGNED(4) const u8 gText_FacilitySingle[] = _("{STR_VAR_1} 싱글");
ALIGNED(4) const u8 gText_FacilityDouble[] = _("{STR_VAR_1} 더블");
ALIGNED(4) const u8 gText_FacilityMulti[] = _("{STR_VAR_1} 멀티");
ALIGNED(4) const u8 gText_FacilityLink[] = _("{STR_VAR_1} 통신");
ALIGNED(4) const u8 gText_Facility[] = _("{STR_VAR_1}");

const u8 gText_Give[] = _("건네주어야 한다");
const u8 gText_NoNeed[] = _("건네주지 않는다");
const u8 gText_AnnouncingResults[] = _("결과 발표!");
const u8 gText_PreliminaryResults[] = _("1차 심사 결과!");
const u8 gText_Round2Results[] = _("2차 심사 결과!");
const u8 gText_ContestantsMonWon[] = _("우승! {STR_VAR_1}의 {STR_VAR_2}!");
const u8 gText_CommunicationStandby[] = _("통신 대기 중...");
const u8 gText_ColorDarkGray[] = _("");
const u8 gText_ColorDynamic6WhiteDynamic5[] = _(""); // Unused
const u8 gText_HealthboxNickname[] = _("");
const u8 gText_EmptySpace2[] = _(" "); // Unused
const u8 gText_HealthboxGender_Male[] = _("{COLOR DYNAMIC_COLOR2}♂");
const u8 gText_HealthboxGender_Female[] = _("{COLOR DYNAMIC_COLOR1}♀");
const u8 gText_HealthboxGender_None[] = _("{COLOR DYNAMIC_COLOR2}");
const u8 gText_Upper[] = _("ABC");
const u8 gText_Lower[] = _("abc");
const u8 gText_Others[] = _("가나다");
const u8 gText_Symbols[] = _("기호");
const u8 gText_Register2[] = _("등록");
const u8 gText_Exit2[] = _("닫는다");
const u8 gText_QuitChatting[] = _("채팅을 그만두겠습니까?");
const u8 gText_RegisterTextWhere[] = _("어디에 등록하겠습니까?");
const u8 gText_RegisterTextHere[] = _("여기에 등록하겠습니까?");
const u8 gText_InputText[] = _("말을 넣어 주십시오!");
const u8 gText_F700JoinedChat[] = _("{DYNAMIC 0}님이 채팅에 참가했습니다!");
const u8 gText_F700LeftChat[] = _("{DYNAMIC 0}님이 나갔습니다");
const u8 gJPText_PlayersXPokemon[] = _("{DYNAMIC 0}의 {DYNAMIC 1}마리째:"); // Unused
const u8 gJPText_PlayersXPokmonDoesNotExist[] = _("{DYNAMIC 0}의 {DYNAMIC 1}마리가 없습니다"); // Unused
const u8 gText_ExitingChat[] = _("참가자가 없으므로\n종료합니다!");
const u8 gText_LeaderLeftEndingChat[] = _("리더인 {DYNAMIC 0}님이\n나갔으므로 해산합니다!");
const u8 gText_RegisteredTextChangedOKToSave[] = _("등록이 바뀌었습니다\n포켓몬 리포트를 작성합니까?");
const u8 gText_AlreadySavedFile_Chat[] = _("전에 작성한 리포트에\n덮어써도 괜찮습니까?");
const u8 gText_SavingDontTurnOff_Chat[] = _("포켓몬 리포트를 작성하고 있습니다\n전원을 끄지 않도록 해주십시오");
const u8 gText_PlayerSavedGame_Chat[] = _("{DYNAMIC 0}{K_EUNNEUN}\n리포트를 꼼꼼히 기록했다!");
const u8 gText_IfLeaderLeavesChatEnds[] = _("리더가 그만두면 해산하게\n됩니다만 괜찮겠습니까?");
const u8 gText_Hello[] = _("안녕");
const u8 gText_Pokemon2[] = _("포켓몬");
const u8 gText_Trade[] = _("교환");
const u8 gText_Battle[] = _("대전");
const u8 gText_Lets[] = _("하자!");
const u8 gText_Ok[] = _("OK!");
const u8 gText_Sorry[] = _("미안...");
const u8 gText_YaySmileEmoji[] = _("우와{EMOJI_BIGSMILE}");
const u8 gText_ThankYou[] = _("땡큐");
const u8 gText_ByeBye[] = _("바이바이!");
const u8 gText_HatchedFromEgg[] = _("알이 부화해서\n{STR_VAR_1}{K_IGA} 태어났다!");
const u8 gText_NicknameHatchPrompt[] = _("태어난 {STR_VAR_1}에게\n별명을 붙일까요?");
ALIGNED(4) const u8 gText_ReadyPickBerry[] = _("나무열매크러시를 시작합니다\n사용할 나무열매를 선택해 주십시오\p");
ALIGNED(4) const u8 gText_WaitForAllChooseBerry[] = _("다른 멤버가 나무열매를\n선택할 때까지 기다려 주십시오");
ALIGNED(4) const u8 gText_EndedWithXUnitsPowder[] = _("{PAUSE_MUSIC}{PLAY_BGM MUS_LEVEL_UP}보슬보슬한 가루가\n{STR_VAR_1}만큼 나왔다!{RESUME_MUSIC}\p전부 합해서 가루의 양이\n{STR_VAR_2}만큼이 되었다!\p");
ALIGNED(4) const u8 gText_RecordingGameResults[] = _("게임의 결과를\n포켓몬 리포트에 작성 중입니다\l잠시 기다려 주십시오");
ALIGNED(4) const u8 gText_PlayBerryCrushAgain[] = _("나무열매크러시를 한 번 더\n플레이하겠습니까?");
ALIGNED(4) const u8 gText_YouHaveNoBerries[] = _("사용할 나무열매가 없습니다\n게임을 종료합니다");
ALIGNED(4) const u8 gText_MemberDroppedOut[] = _("나간 멤버가 있으므로\n게임을 종료합니다");
ALIGNED(4) const u8 gText_TimesUpNoGoodPowder[] = _("시간이 다 되었습니다\p좋은 가루가\n만들어지지 못했습니다\p");
ALIGNED(4) const u8 gText_CommunicationStandby2[] = _("통신 대기 중");
ALIGNED(4) const u8 gText_1DotBlueF700[] = _("1. {COLOR BLUE}{SHADOW LIGHT_BLUE}{DYNAMIC 0}");
ALIGNED(4) const u8 gText_1DotF700[] = _("1. {DYNAMIC 0}");
ALIGNED(4) const u8 gText_SpaceTimes2[] = _("회");
ALIGNED(4) const u8 gText_XDotY[] = _("{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_Var1Berry[] = _("{STR_VAR_1}열매");
ALIGNED(4) const u8 gText_TimeColon[] = _("시간");
ALIGNED(4) const u8 gText_PressingSpeed[] = _("누른 속도");
ALIGNED(4) const u8 gText_Silkiness[] = _("보슬보슬함");
ALIGNED(4) const u8 gText_StrVar1[] = _("{STR_VAR_1}");
ALIGNED(4) const u8 gText_SpaceMin[] = _("분 ");
ALIGNED(4) const u8 gText_XDotY2[] = _("{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_SpaceSec[] = _("초");
ALIGNED(4) const u8 gText_XDotY3[] = _("{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_TimesPerSec[] = _("회/초");
ALIGNED(4) const u8 gText_Var1Percent[] = _("{STR_VAR_1}%");
ALIGNED(4) const u8 gText_PressesRankings[] = _("누른 횟수 랭킹");
ALIGNED(4) const u8 gText_CrushingResults[] = _("부순 결과");
ALIGNED(4) const u8 gText_NeatnessRankings[] = _("신중함 랭킹");
ALIGNED(4) const u8 gText_CoopRankings[] = _("협력 랭킹");
ALIGNED(4) const u8 gText_PressingPowerRankings[] = _("누른 세기 랭킹");
const u8 gText_BerryCrush2[] = _("나무열매크러시");
const u8 gText_PressingSpeedRankings[] = _("누른 속도 랭킹");
const u8 gText_Var1Players[] = _("{STR_VAR_1}인용");
const u8 gText_SymbolsEarned[] = _("손에 넣은 심볼");
const u8 gText_BattleRecord[] = _("대전 기록");
const u8 gText_BattlePoints[] = _("배틀포인트");
const u8 gText_UnusedCancel[] = _("닫는다"); // Unused
const u8 gText_EmptyString7[] = _("");
const u8 gText_CheckFrontierMap[] = _("배틀프런티어의 맵을 봅니다");
const u8 gText_CheckTrainerCard[] = _("트레이너카드를 봅니다");
const u8 gText_ViewRecordedBattle[] = _("기록한 대전을 봅니다");
const u8 gText_PutAwayFrontierPass[] = _("프런티어패스를 닫습니다");
const u8 gText_CurrentBattlePoints[] = _("지금 가진 배틀포인트입니다");
const u8 gText_CollectedSymbols[] = _("여기에 심볼을 모읍니다");
const u8 gText_BattleTowerAbilitySymbol[] = _("배틀타워 어빌리티심볼");
const u8 gText_BattleDomeTacticsSymbol[] = _("배틀돔 택틱스심볼");
const u8 gText_BattlePalaceSpiritsSymbol[] = _("배틀팰리스 스피릿심볼");
const u8 gText_BattleArenaGutsSymbol[] = _("배틀아레나 거츠심볼");
const u8 gText_BattleFactoryKnowledgeSymbol[] = _("배틀팩토리 놀리지심볼");
const u8 gText_BattlePikeLuckSymbol[] = _("배틀튜브 럭심볼");
const u8 gText_BattlePyramidBraveSymbol[] = _("배틀피라미드 브레이브심볼");
const u8 gText_ThereIsNoBattleRecord[] = _("현재 대전 기록이 없습니다");
const u8 gText_BattleTower3[] = _("배틀타워");
const u8 gText_BattleDome2[] = _("배틀돔");
const u8 gText_BattlePalace2[] = _("배틀팰리스");
const u8 gText_BattleArena2[] = _("배틀아레나");
const u8 gText_BattleFactory2[] = _("배틀팩토리");
const u8 gText_BattlePike2[] = _("배틀튜브");
const u8 gText_BattlePyramid2[] = _("배틀피라미드");
const u8 gText_BattleTowerDesc[] = _("연승하여 오로지 위를 향한다.\n재능을 시험받는다.");
const u8 gText_BattleDomeDesc[] = _("토너먼트를 연승해 나간다.\n전술을 시험받는다.");
const u8 gText_BattlePalaceDesc[] = _("승부를 지켜본다.\n포켓몬과의 유대감을 시험받는다.");
const u8 gText_BattleArenaDesc[] = _("강한 포켓몬 팀으로 승리한다.\n투지를 시험받는다.");
const u8 gText_BattleFactoryDesc[] = _("대여 포켓몬으로 승리한다.\n지식을 시험받는다.");
const u8 gText_BattlePikeDesc[] = _("3개의 길 중 1개를 골라 이겨 나간다.\n운을 시험받는다.");
const u8 gText_BattlePyramidDesc[] = _("정상을 향해 모험한다.\n용기를 시험받는다.");
const u8 gText_Powder[] = _("나무열매가루");
const u8 gText_BerryPickingRecords[] = _("두트리오 나무열매먹기의 기록");
const u8 gText_BerriesPicked[] = _("나무열매를 먹은 횟수");
const u8 gText_BestScore[] = _("최고 득점");
const u8 gText_BerriesInRowFivePlayers[] = _("5명이 나무열매를\n이어서 먹은 횟수");
const u8 gText_BerryPickingResults[] = _("나무열매 결과 발표!!");
const u8 gText_10P30P50P50P[] = _("{CLEAR_TO 0x03}10P{CLEAR_TO 0x2B}30P{CLEAR_TO 0x53}50P{CLEAR_TO 0x77}{EMOJI_MINUS}50P");
const u8 gText_AnnouncingRankings[] = _("순위 발표!!");
const u8 gText_AnnouncingPrizes[] = _("상품 발표!!");
const u8 gText_1Colon[] = _("1:");
const u8 gText_2Colon[] = _("2:");
const u8 gText_3Colon[] = _("3:");
const u8 gText_4Colon[] = _("4:");
const u8 gText_5Colon[] = _("5:");
const u8 gText_FirstPlacePrize[] = _("1번이 된 사람에게\n{DYNAMIC 0}{K_EULREUL} 선물!!");
const u8 gText_CantHoldAnyMore[] = _("{DYNAMIC 0}{K_IGA} 가득합니다...");
const u8 gText_FilledStorageSpace[] = _("{DYNAMIC 0}{K_IGA} 가득하게 되었다!");
const u8 gText_WantToPlayAgain[] = _("다시 한 번 놀겠습니까?");
const u8 gText_SomeoneDroppedOut[] = _("누군가가 나갔습니다\n통신을 종료합니다");
const u8 gText_SpacePoints[] = _("점");
const u8 gText_CommunicationStandby3[] = _("통신 대기 중입니다");
const u8 gText_SpacePoints2[] = _("점");
const u8 gText_SpaceTimes3[] = _("회");
const u8 gText_PkmnJumpRecords[] = _("미니 포켓몬 점프의 기록");
const u8 gText_JumpsInARow[] = _("최고 점프 횟수");
const u8 gText_BestScore2[] = _("최고 득점");
const u8 gText_ExcellentsInARow[] = _("연속 EXCELLENT");
const u8 gText_AwesomeWonF701F700[] = _("성적이 좋았으므로\n{DYNAMIC 0}{K_EULREUL} {DYNAMIC 1}개 선물!");
const u8 gText_FilledStorageSpace2[] = _("{DYNAMIC 0}{K_IGA}\n가득하게 되었다!");
const u8 gText_CantHoldMore[] = _("{DYNAMIC 0}{K_IGA} 가득합니다...");
const u8 gText_WantToPlayAgain2[] = _("한 번 더 플레이하겠습니까?");
const u8 gText_SomeoneDroppedOut2[] = _("누군가가 나갔습니다\n통신을 종료합니다");
const u8 gText_CommunicationStandby4[] = _("통신 대기 중");
const u8 gText_LinkContestResults[] = _("{PLAYER}의 통신 콘테스트 성적");
const u8 gText_1st[] = _("1위");
const u8 gText_2nd[] = _("2위");
const u8 gText_3rd[] = _("3위");
const u8 gText_4th[] = _("4위");
const u8 gText_Friend[] = _("친구");
const u8 gText_Pokemon3[] = _("pokemon"); // Unused
const u8 gJPText_MysteryGift[] = _("이상한 소포");
const u8 gJPText_DecideStop[] = _("{A_BUTTON}결정 {B_BUTTON}그만둔다");
const u8 gJPText_ReceiveMysteryGiftWithEReader[] = _("카드 e 리더{PLUS}로\n이상한 소포를 읽습니다");
const u8 gJPText_SelectConnectFromEReaderMenu[] = _("카드 e 리더{PLUS}의 메뉴에서\n‘통신'을 선택하고");
const u8 gJPText_SelectConnectWithGBA[] = _("‘게임보이 어드밴스와 통신'을\n선택해 주십시오");
const u8 gJPText_SelectConnectAndPressA[] = _("카드 e 리더{PLUS}의 ‘통신'을\n선택하고 A 버튼을 눌러 주십시오"); // Unused
const u8 gJPText_LinkIsIncorrect[] = _("접속이 잘못되었습니다");
const u8 gJPText_CardReadingHasBeenHalted[] = _("카드 읽기를\n중지했습니다");
const u8 gJPText_UnableConnectWithEReader[] = _("카드 e 리더{PLUS}와\n통신할 수 없습니다"); // Unused
const u8 gJPText_Connecting[] = _("통신 중입니다");
const u8 gJPText_ConnectionErrorCheckLink[] = _("통신 에러입니다\n접속을 확인해 주십시오");
const u8 gJPText_ConnectionErrorTryAgain[] = _("통신 에러입니다\n처음부터 다시 한 번 시도해 주십시오"); // Link error
const u8 gJPText_AllowEReaderToLoadCard[] = _("카드 e 리더{PLUS}가\n카드를 읽도록 해주십시오");
const u8 gJPText_ConnectionComplete[] = _("통신 종료!");
const u8 gJPText_NewTrainerHasComeToHoenn[] = _("새로운 트레이너가\n호연지방에 찾아왔다!");
const u8 gJPText_PleaseWaitAMoment[] = _("잠시 기다려 주십시오");
const u8 gJPText_WriteErrorUnableToSaveData[] = _("쓰기 에러입니다\n데이터를 저장할 수 없었습니다");
const u8 gText_SingleBattleRoomResults[] = _("{PLAYER}의 싱글 배틀룸 성적");
const u8 gText_DoubleBattleRoomResults[] = _("{PLAYER}의 더블 배틀룸 성적");
const u8 gText_MultiBattleRoomResults[] = _("{PLAYER}의 멀티 배틀룸 성적");
const u8 gText_LinkMultiBattleRoomResults[] = _("{PLAYER}의 통신멀티 배틀룸 성적");
const u8 gText_SingleBattleTourneyResults[] = _("{PLAYER}의 싱글 배틀토너먼트 성적");
const u8 gText_DoubleBattleTourneyResults[] = _("{PLAYER}의 더블 배틀토너먼트 성적");
const u8 gText_SingleBattleHallResults[] = _("{PLAYER}의 싱글 배틀홀 성적");
const u8 gText_DoubleBattleHallResults[] = _("{PLAYER}의 더블 배틀홀 성적");
const u8 gText_BattleChoiceResults[] = _("{PLAYER}의 배틀게임 성적");
const u8 gText_SetKOTourneyResults[] = _("{PLAYER}의 연승팀배틀 성적");
const u8 gText_BattleSwapSingleResults[] = _("{PLAYER}의 배틀트레이드 싱글 성적");
const u8 gText_BattleSwapDoubleResults[] = _("{PLAYER}의 배틀트레이드 더블 성적");
const u8 gText_BattleQuestResults[] = _("{PLAYER}의 배틀어드벤처 성적");
const u8 gText_Lv502[] = _("레벨 50");
const u8 gText_OpenLv[] = _("오픈 레벨");
const u8 gText_WinStreak[] = _("{STR_VAR_1}연승");
const u8 gText_Current[] = _("현재");
const u8 gText_Record[] = _("최고");
const u8 gText_Prev[] = _("지난번");
const u8 gText_RentalSwap[] = _("대여/교환");
const u8 gText_Total[] = _("통산");
const u8 gText_ClearStreak[] = _("{STR_VAR_1}연패");
const u8 gText_Championships[] = _("{STR_VAR_1}회 우승");
const u8 gText_RoomsCleared[] = _("{STR_VAR_1}방 돌파");
const u8 gText_TimesCleared[] = _("{STR_VAR_1}회 클리어");
const u8 gText_KOsInARow[] = _("{STR_VAR_1}명 돌파");
const u8 gText_TimesVar1[] = _("{STR_VAR_1}회");
const u8 gText_FloorsCleared[] = _("{STR_VAR_1}단 제패");

ALIGNED(4) const u8 gText_RecordsLv50[] = _("레벨 50");
ALIGNED(4) const u8 gText_RecordsOpenLevel[] = _("오픈 레벨");
ALIGNED(4) const u8 gText_FrontierFacilityWinStreak[] = _("{STR_VAR_2}연승");
ALIGNED(4) const u8 gText_FrontierFacilityClearStreak[] = _("{STR_VAR_2}연패");
ALIGNED(4) const u8 gText_FrontierFacilityRoomsCleared[] = _("{STR_VAR_2}방 돌파");
ALIGNED(4) const u8 gText_FrontierFacilityKOsStreak[] = _("{STR_VAR_2}명 돌파");
ALIGNED(4) const u8 gText_FrontierFacilityFloorsCleared[] = _("{STR_VAR_2}단 제패");
ALIGNED(4) const u8 gText_123Dot[][3] = {_("1."), _("2."), _("3.")};
const u8 gText_FrontierFacilityTotalCaughtSpeciesBanned[] = _("{K_WAGWA} 잡은 포켓몬 중\n{STR_VAR_2}종은 참가시킬 수 없습니다!");
const u8 gText_FrontierFacilityIncluding[] = _(".\p해당 포켓몬: ");
const u8 gText_FrontierFacilityAreInelegible[] = _("은 참가시킬 없습니다!");

const u8 gText_YesNo[] = _("예\n아니오");
const u8 gText_SelectorArrow3[] = _("▶");
const u8 gText_Peekaboo[] = _("까꿍!");
const u8 gText_CommErrorCheckConnections[] = _("통신 에러가 발생했습니다\n{CLEAR 11}주변 기기와의 접속을\n{CLEAR 11}제대로 확인하고 나서\n{CLEAR 4}전원을 다시 켜 주십시오");
const u8 gText_CommErrorEllipsis[] = _("통신 에러가 발생했습니다");
const u8 gText_MoveCloserToLinkPartner[] = _("통신 에러가 발생했습니다\n  통신 상대와 가까이 있고\n장애물이 없도록 해주십시오");
const u8 gText_ABtnRegistrationCounter[] = _("A 버튼으로\n접수처로 돌아갑니다");
const u8 gText_ABtnTitleScreen[] = _("A 버튼으로\n타이틀 화면으로 돌아갑니다");
const u8 gText_NumPlayerLink[] = _("{STR_VAR_1}인 접속");
const u8 gText_BronzeCard[] = _("브론즈");
const u8 gText_CopperCard[] = _("코퍼");
const u8 gText_SilverCard[] = _("실버");
const u8 gText_GoldCard[] = _("골드");
const u8 gText_Day[] = _("날짜");
const u8 gText_Colon3[] = _(":");
const u8 gText_Confirm2[] = _("확인");
const u8 gText_Days[] = _("날짜"); // Unused
const u8 gText_TimeColon2[] = _("시간:"); // Unused
const u8 gText_GameTime[] = _("게임 시간"); // Unused
const u8 gText_RTCTime[] = _("RTC 시간"); // Unused
const u8 gText_UpdatedTime[] = _("갱신된 시간"); // Unused
const u8 gText_MenuPokedex[] = _("도감");
const u8 gText_MenuPokemon[] = _("포켓몬");
const u8 gText_MenuBag[] = _("가방");
#if IS_HNS
const u8 gText_MenuPokenav[] = _("포켓기어");
#else
const u8 gText_MenuPokenav[] = _("포켓내비");
#endif
const u8 gText_MenuPlayer[] = _("{PLAYER}");
const u8 gText_MenuSave[] = _("리포트");
const u8 gText_MenuOption[] = _("설정");
const u8 gText_MenuExit[] = _("닫는다");
const u8 gText_MenuRetire[] = _("포기한다");
const u8 gText_MenuRest[] = _("쉰다");
const u8 gText_MenuDexNav[] = _("도감 내비");
const u8 gText_SafariBallStock[] = _("사파리볼\n{STR_VAR_1}개 남음");
const u8 gText_MenuSafariStats[] = _("{STR_VAR_1}/{STR_VAR_2}\nBALLS  {STR_VAR_3}");
const u8 gText_BattlePyramidFloor[] = _("배틀피라미드\n{STR_VAR_1}");
const u8 gText_Floor1[] = _("현재 1단째");
const u8 gText_Floor2[] = _("현재 2단째");
const u8 gText_Floor3[] = _("현재 3단째");
const u8 gText_Floor4[] = _("현재 4단째");
const u8 gText_Floor5[] = _("현재 5단째");
const u8 gText_Floor6[] = _("현재 6단째");
const u8 gText_Floor7[] = _("현재 7단째");
const u8 gText_Peak[] = _("현재 정상");
const u8 gText_LinkStandby2[] = _("통신 대기 중입니다\n......B 버튼으로 취소합니다");
const u8 gText_PressAToLoadEvent[] = _("A 버튼으로 사건을 읽어들입니다\n......B 버튼으로 취소합니다");
const u8 gText_LoadingEvent[] = _("사건을 읽어들이는 중!!");
const u8 gText_DontRemoveCableTurnOff[] = _("통신케이블을 뽑지 말아 주십시오\n전원을 끄지 않도록 해주십시오");
const u8 gText_EventSafelyLoaded[] = _("사건의 로딩이\n정상적으로 종료되었습니다");
const u8 gText_LoadErrorEndingSession[] = _("에러가 발생했습니다\n종료합니다");
const u8 gJPText_Player[] = _("플레이어"); // Unused
const u8 gJPText_Sama[] = _("님"); // Unused
const u8 gText_DexHoenn[] = _("호연");
const u8 gText_DexNational[] = _("전국");
const u8 gText_PokedexDiploma[] = _("플레이어 {CLEAR 0x10}{COLOR RED}{SHADOW LIGHT_RED}{PLAYER}님\n\n{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}{STR_VAR_1} 포켓몬 도감을\n훌륭히 완성시킨\n위대한 공적을 기려서\n이에 증명합니다\n\n{CLEAR_TO 0x42}{COLOR RED}{SHADOW LIGHT_RED}GAME FREAK");
const u8 gJPText_GameFreak[] = _("{COLOR RED}{SHADOW LIGHT_RED}GAME FREAK"); // Unused
const u8 gText_DiplomaEmpty[] = _("{COLOR RED}{SHADOW LIGHT_RED}"); // Unused
const u8 gText_Hoenn[] = _("호연지방");
const u8 gText_Kanto[] = _("관동지방");
const u8 gText_Johto[] = _("성도지방");
const u8 gText_JohtoKanto[] = _("성도지방 & 관동지방");
const u8 gText_XWillBeSentToY[] = _("{STR_VAR_2}{K_EULREUL} {STR_VAR_1}에게 보냅니다!");
const u8 gText_ByeByeVar1[] = _("바이바이 {STR_VAR_2}!");
const u8 gText_XSentOverY[] = _("{STR_VAR_1}{K_EU}로부터 {STR_VAR_3}{K_IGA} 전송됐다!");
const u8 gText_TakeGoodCareOfX[] = _("{STR_VAR_3}{K_EULREUL} 귀여워해 줘!");

const u8 gText_ThreeQuestionMarks[] = _("???");
const u8 gText_FourQuestionMarks[] = _("????");
const u8 gText_MaxHP[] = _("최대HP");
const u8 gText_Attack[] = _("공격");
const u8 gText_Defense[] = _("방어");
const u8 gText_Speed[] = _("스피드");
const u8 gText_SpAtk[] = _("특수공격");
const u8 gText_SpDef[] = _("특수방어");
const u8 gText_Plus[] = _("{PLUS}");
const u8 gText_Dash[] = _("-");
const u8 gText_MixingRecords[] = _("레코드를 섞고 있습니다");
const u8 gText_RecordMixingComplete[] = _("레코드 통신이 끝났습니다!\n수고하셨습니다");
const u8 gText_RentalPkmn2[] = _("포켓몬 대여");
const u8 gText_SelectFirstPkmn[] = _("1번째 포켓몬을 선택해 주십시오");
const u8 gText_SelectSecondPkmn[] = _("2번째 포켓몬을 선택해 주십시오");
const u8 gText_SelectThirdPkmn[] = _("3번째 포켓몬을 선택해 주십시오");
const u8 gText_Rent[] = _("대여받는다");
const u8 gText_Summary[] = _("능력치 보기");
const u8 gText_Others2[] = _("닫는다");
const u8 gText_Deselect[] = _("떼어낸다");
const u8 gText_TheseThreePkmnOkay[] = _("Are these three POKéMON OK?");
const u8 gText_Yes2[] = _("예");
const u8 gText_No2[] = _("아니오");
const u8 gText_CantSelectSamePkmn[] = _("같은 포켓몬은 선택할 수 없습니다");
const u8 gText_PkmnSwap[] = _("포켓몬 교환");
const u8 gText_SelectPkmnToSwap[] = _("교환할 포켓몬을 선택해 주십시오");
const u8 gText_SelectPkmnToAccept[] = _("받을 포켓몬을 선택해 주십시오");
const u8 gText_Swap[] = _("교환한다");
const u8 gText_Summary2[] = _("능력치 보기");
const u8 gText_Rechoose[] = _("닫는다");
const u8 gText_QuitSwapping[] = _("교환을 중지하겠습니까?");
const u8 gText_Yes3[] = _("예");
const u8 gText_No3[] = _("아니오");
const u8 gText_PkmnForSwap[] = _("교환할 포켓몬");
const u8 gText_Cancel3[] = _("중지");
const u8 gText_Swap2[] = _("교환한다"); // Unused
const u8 gText_Accept[] = _("받는다"); // Unused
const u8 gText_AcceptThisPkmn[] = _("이 포켓몬을 받겠습니까?");
const u8 gText_4Spaces[] = _("    "); // Unused
const u8 gText_SamePkmnInPartyAlready[] = _("같은 포켓몬이 있습니다!");
const u8 gText_DecimalPoint[] = _(".");
const u8 gText_SavingPlayer[] = _("주인공");
const u8 gText_SavingBadges[] = _("가진 배지");
const u8 gText_SavingPokedex[] = _("포켓몬 도감");
const u8 gText_SavingTime[] = _("플레이 시간");
const u8 gText_WirelessCommStatus[] = _("무선 통신 상황");
const u8 gText_PeopleTrading[] = _("교환 중인 사람");
const u8 gText_PeopleBattling[] = _("대전 중인 사람");
const u8 gText_PeopleInUnionRoom[] = _("유니언 룸에 있는 사람");
const u8 gText_PeopleCommunicating[] = _("통신 중인 사람");
const u8 gText_F700Players[] = _("{DYNAMIC 0}인");
const u8 gText_F701Players[] = _("{DYNAMIC 1}인");
const u8 gText_F702Players[] = _("{DYNAMIC 2}인");
const u8 gText_F703Players[] = _("{DYNAMIC 3}인");

const u8 *const gTextTable_Players[] = {
    gText_F700Players,
    gText_F701Players,
    gText_F702Players,
    gText_F703Players
};

ALIGNED(4) const u8 gText_WonderCards[] = _("이상한 카드");
ALIGNED(4) const u8 gText_WonderNews[] = _("이상한 뉴스");
ALIGNED(4) const u8 gText_WirelessCommunication[] = _("조이스폿");
ALIGNED(4) const u8 gText_Friend2[] = _("친구");
ALIGNED(4) const u8 gText_Exit3[] = _("그만둔다");
ALIGNED(4) const u8 gText_Receive[] = _("읽어들인다");
ALIGNED(4) const u8 gText_Send[] = _("보낸다");
ALIGNED(4) const u8 gText_Toss[] = _("버린다");
ALIGNED(4) const u8 gText_VarietyOfEventsImportedWireless[] = _("무선으로 여러 사건들을\n읽습니다");
ALIGNED(4) const u8 gText_WonderCardsInPossession[] = _("가지고 있는 이상한 카드를\n볼 수 있습니다");
ALIGNED(4) const u8 gText_ReadNewsThatArrived[] = _("보내진 뉴스를\n볼 수 있습니다");
ALIGNED(4) const u8 gText_ReturnToTitle[] = _("타이틀 화면으로 돌아갑니다");
ALIGNED(4) const u8 gText_DontHaveCardNewOneInput[] = _("이상한 카드를 가지고 있지 않으므로\n새로운 카드를 읽습니다");
ALIGNED(4) const u8 gText_DontHaveNewsNewOneInput[] = _("이상한 뉴스를 가지고 있지 않으므로\n새로운 뉴스를 읽습니다");
ALIGNED(4) const u8 gText_WhereShouldCardBeAccessed[] = _("어느 쪽에서 이상한 카드를\n읽겠습니까?");
ALIGNED(4) const u8 gText_WhereShouldNewsBeAccessed[] = _("어느 쪽에서 이상한 뉴스를\n읽겠습니까?");
ALIGNED(4) const u8 gText_CommunicationStandbyBButtonCancel[] = _("통신 대기 중입니다\n...B 버튼으로 취소합니다"); // Unused
ALIGNED(4) const u8 gText_Communicating[] = _("통신하고 있습니다...");
ALIGNED(4) const u8 gText_CommunicationCompleted[] = _("통신을 종료했습니다");
ALIGNED(4) const u8 gText_CommunicationError[] = _("통신에 실패했습니다");
ALIGNED(4) const u8 gText_CommunicationCanceled[] = _("통신을 취소했습니다");
ALIGNED(4) const u8 gText_ThrowAwayWonderCard[] = _("이 이상한 카드를 버리고\n새로운 카드를 읽겠습니까?");
ALIGNED(4) const u8 gText_HaventReceivedCardsGift[] = _("아직 카드의 소포를 받지\n않았습니다만 정말로 읽겠습니까?");
ALIGNED(4) const u8 gText_WonderCardReceivedFrom[] = _("{STR_VAR_1}{K_EU}부터 이상한 카드가\n전송되었습니다!");
ALIGNED(4) const u8 gText_WonderNewsReceivedFrom[] = _("{STR_VAR_1}{K_EU}부터 뉴스가\n전송되었습니다!");
ALIGNED(4) const u8 gText_WonderCardReceived[] = _("새로운 이상한 카드가\n전송되었습니다!");
ALIGNED(4) const u8 gText_WonderNewsReceived[] = _("새로운 뉴스가\n전송되었습니다!");
ALIGNED(4) const u8 gText_NewStampReceived[] = _("새로운 스탬프가\n전송되었습니다!");
ALIGNED(4) const u8 gText_NewTrainerReceived[] = _("새로운 트레이너가\n전송되었습니다!");
ALIGNED(4) const u8 gText_AlreadyHadCard[] = _("같은 이상한 카드를\n이미 가지고 있습니다");
ALIGNED(4) const u8 gText_AlreadyHadNews[] = _("같은 뉴스를\n이미 가지고 있습니다");
ALIGNED(4) const u8 gText_AlreadyHadStamp[] = _("같은 스탬프를\n이미 가지고 있습니다");
ALIGNED(4) const u8 gText_NoMoreRoomForStamps[] = _("스탬프가 가득 찼으므로\n더 받을 수 없습니다!");
ALIGNED(4) const u8 gText_RecordUploadedViaWireless[] = _("자신의 기록을\n조이스폿에 올렸습니다!");
ALIGNED(4) const u8 gText_CantAcceptCardFromTrainer[] = _("이 상대로부터는 이상한 카드를\n받을 수 없습니다!");
ALIGNED(4) const u8 gText_CantAcceptNewsFromTrainer[] = _("이 상대로부터는 뉴스를\n받을 수 없습니다!");
ALIGNED(4) const u8 gText_NothingSentOver[] = _("아무것도 전송되지\n않았습니다");
ALIGNED(4) const u8 gText_WhatToDoWithCards[] = _("카드를 어떻게 하겠습니까?");
ALIGNED(4) const u8 gText_WhatToDoWithNews[] = _("뉴스를 어떻게 하겠습니까?");
ALIGNED(4) const u8 gText_SendingWonderCard[] = _("이상한 카드를\n전송하고 있습니다...");
ALIGNED(4) const u8 gText_SendingWonderNews[] = _("뉴스를\n전송하고 있습니다...");
ALIGNED(4) const u8 gText_WonderCardSentTo[] = _("{STR_VAR_1}에게 이상한 카드를\n전송했습니다!");
ALIGNED(4) const u8 gText_WonderNewsSentTo[] = _("{STR_VAR_1}에게 뉴스를\n전송했습니다!");
ALIGNED(4) const u8 gText_StampSentTo[] = _("{STR_VAR_1}에게 스탬프를\n전송했습니다!");
ALIGNED(4) const u8 gText_GiftSentTo[] = _("{STR_VAR_1}에게 선물을 전송했습니다!");
ALIGNED(4) const u8 gText_OtherTrainerHasCard[] = _("상대가 같은\n이상한 카드를 가지고 있습니다!");
ALIGNED(4) const u8 gText_OtherTrainerHasNews[] = _("상대가 같은\n뉴스를 가지고 있습니다!");
ALIGNED(4) const u8 gText_OtherTrainerHasStamp[] = _("상대가 같은\n스탬프를 가지고 있습니다!");
ALIGNED(4) const u8 gText_OtherTrainerCanceled[] = _("상대가 통신을\n취소했습니다");
ALIGNED(4) const u8 gText_CantSendGiftToTrainer[] = _("이 상대에게는\n이상한 소포를 보낼 수 없습니다");
ALIGNED(4) const u8 gText_IfThrowAwayCardEventWontHappen[] = _("카드를 버리면 사건이\n없어지게 됩니다만 괜찮겠습니까?");
ALIGNED(4) const u8 gText_OkayToDiscardNews[] = _("정말로 뉴스를\n버려도 괜찮겠습니까?");
ALIGNED(4) const u8 gText_HaventReceivedGiftOkayToDiscard[] = _("소포를 받지 않았습니다만\n정말로 버리겠습니까?");
ALIGNED(4) const u8 gText_DataWillBeSaved[] = _("리포트를 작성하고 있습니다\n잠시 기다려 주십시오");
ALIGNED(4) const u8 gText_SaveCompletedPressA[] = _("리포트를 작성했습니다!\nA 버튼을 눌러 주십시오");
ALIGNED(4) const u8 gText_WonderCardThrownAway[] = _("이상한 카드를 버렸습니다");
ALIGNED(4) const u8 gText_WonderNewsThrownAway[] = _("뉴스를 버렸습니다");
ALIGNED(4) const u8 gText_MysteryGift[] = _("이상한 소포");
ALIGNED(4) const u8 gText_PickOKExit[] = _("{DPAD_UPDOWN}선택한다 {A_BUTTON}결정 {B_BUTTON}그만둔다");
ALIGNED(4) const u8 gText_PickOKCancel[] = _("{DPAD_UPDOWN}선택한다 {A_BUTTON}결정 {B_BUTTON}그만둔다");
const u8 gText_PlayersBattleResults[] = _("{PLAYER}의 대전 성적");
const u8 gText_TotalRecordWLD[] = _("{STR_VAR_1}승 {STR_VAR_2}패 {STR_VAR_3}무승부");
const u8 gText_WinLoseDraw[] = _("{CLEAR_TO 0x53}승{CLEAR_TO 0x80}패{CLEAR_TO 0xB0}무승부");
const u8 gText_CommunicationStandby5[] = _("통신 대기 중...");
const u8 gDaycareText_GetAlongVeryWell[] = _("2마리는 사이가\n아주 좋은 것 같구먼!");
const u8 gDaycareText_GetAlong[] = _("2마리는 사이가\n그럭저럭인 것 같구먼");
const u8 gDaycareText_DontLikeOther[] = _("2마리의 사이가\n그다지 좋지 않구먼");
const u8 gDaycareText_PlayOther[] = _("2마리는 서로\n다른 포켓몬과 놀고 있구먼...");
const u8 gText_NewLine2[] = _("\n");
const u8 gText_Exit4[] = _("취소");
const u8 gText_Lv[] = _("{LV}");
const u8 gText_TimeBoard[] = _("타임보드");
const u8 gText_TimeCleared[] = _("클리어타임");
const u8 gText_XMinYDotZSec[] = _(" {STR_VAR_1}분 {STR_VAR_2}.{STR_VAR_3}초");
const u8 gText_TrainerHill1F[] = _("1F");
const u8 gText_TrainerHill2F[] = _("2F");
const u8 gText_TrainerHill3F[] = _("3F");
const u8 gText_TrainerHill4F[] = _("4F");
const u8 gText_TeachWhichMoveToPkmn[] = _("{STR_VAR_1}에게\n어느 기술을 배우게 하겠습니까?");
const u8 gText_MoveRelearnerTeachMoveConfirm[] = _("{STR_VAR_2}{K_EULREUL}\n배우게 하겠습니까?");
const u8 gText_MoveRelearnerPkmnLearnedMove[] = _("{STR_VAR_1}{K_EUNNEUN} 새로\n{STR_VAR_2}{K_EULREUL} 배웠다!");
const u8 gText_MoveRelearnerPkmnTryingToLearnMove[] = _("{STR_VAR_1}{K_EUNNEUN} 새로\n{STR_VAR_2}{K_EULREUL} 배우고 싶다...\p그러나 {STR_VAR_1}{K_EUNNEUN} 기술을 4개\n알고 있어 더 이상 배울 수 없다!\p{STR_VAR_2} 대신\n다른 기술을 잊게 하겠습니까?");
const u8 gText_MoveRelearnerStopTryingToTeachMove[] = _("그럼...{STR_VAR_2}{K_EULREUL}\n배우는 것을 포기하겠습니까?");
const u8 gText_MoveRelearnerAndPoof[] = _("{PAUSE 32}1 {PAUSE 15}2 {PAUSE 15}...{PAUSE 15}...{PAUSE 15}...{PAUSE 15} {PLAY_SE 0x0038}짠!\p");
const u8 gText_MoveRelearnerPkmnForgotMoveAndLearnedNew[] = _("{STR_VAR_1}{K_EUNNEUN} {STR_VAR_3}{K_EULREUL}\n깨끗이 잊었다!\p그리고...!\p{STR_VAR_1}{K_EUNNEUN} 새로\n{STR_VAR_2}{K_EULREUL} 배웠다!");
const u8 gText_MoveRelearnedPkmnDidNotLearnMove[] = _("{STR_VAR_1}{K_EUNNEUN} {STR_VAR_2}{K_EULREUL}\n결국 배우지 않았다!"); // Unused
const u8 gText_MoveRelearnerGiveUp[] = _("그럼... {STR_VAR_1}에게 기술을\n배우게 하는 것을 포기하겠습니까?");
const u8 gText_MoveRelearnerWhichMoveToForget[] = _("어느 기술을\n잊게 하겠습니까?\p");
const u8 gText_MoveRelearnerBattleMoves[] = _("싸울 기술");
const u8 gText_MoveRelearnerContestMovesTitle[] = _("콘테스트 기술");
const u8 gText_MoveRelearnerType[] = _("타입/"); // Unused
const u8 gText_MoveRelearnerPP[] = _("PP/");
const u8 gText_MoveRelearnerPower[] = _("위력/");
const u8 gText_MoveRelearnerAccuracy[] = _("명중/");
const u8 gText_MoveRelearnerAppeal[] = _("어필");
const u8 gText_MoveRelearnerJam[] = _("방해");
const u8 gText_ClearAllSaveData[] = _("모든 저장 데이터를\n정리하겠습니까?");
const u8 gText_ClearingData[] = _("정리하고 있습니다...\n잠시 기다려 주십시오");
const u8 gText_IsThisTheCorrectTime[] = _("정말 이 시간이 맞습니까?");
const u8 gText_Confirm3[] = _("결정");
const u8 gText_Cancel4[] = _("돌아간다");
const u8 gText_CommStandbyAwaitingOtherPlayer[] = _("통신 대기 중\n상대의 선택을 기다리고 있습니다...");
const u8 gText_BattleWasRefused[] = _("대전이 거절되었습니다{PAUSE 60}");
const u8 gText_RefusedBattle[] = _("대전을 사양했습니다{PAUSE 60}");
const u8 gText_NoWeather[] = _("NO WEATHER"); // Below are unused debug names for weather types
const u8 gText_Sunny[] = _("SUNNY"); // Unused
const u8 gText_Sunny2[] = _("SUNNY2"); // Unused
const u8 gText_Rain[] = _("RAIN"); // Unused
const u8 gText_Snow[] = _("SNOW"); // Unused
const u8 gText_Lightning[] = _("LIGHTNING"); // Unused
const u8 gText_Fog[] = _("FOG"); // Unused
const u8 gText_VolcanoAsh[] = _("VOLCANO ASH"); // Unused
const u8 gText_Sandstorm[] = _("SANDSTORM"); // Unused
const u8 gText_Fog2[] = _("FOG2"); // Unused
const u8 gText_Seafloor[] = _("SEAFLOOR"); // Unused
const u8 gText_Cloudy[] = _("CLOUDY"); // Unused
const u8 gText_Sunny3[] = _("SUNNY3"); // Unused
const u8 gText_HeavyRain[] = _("HEAVY RAIN"); // Unused
const u8 gText_Seafloor2[] = _("SEAFLOOR2"); // Unused
const u8 gText_DelAll[] = _("전부 삭제");
const u8 gText_Cancel5[] = _("취소");
const u8 gText_Ok2[] = _("결정");
const u8 gText_Quiz[] = _("퀴즈");
const u8 gText_Answer[] = _("대답");
const u8 gText_PokeBalls[] = _("몬스터볼");
const u8 gText_Berry[] = _("열매");
const u8 gText_Berries[] = _("열매");
const u8 gText_Obtained999RareCandies[] = _("이상한사탕 999개를\n손에 넣었다!{PAUSE_UNTIL_PRESS}");
const u8 gText_ExpShareOn[] = _("학습장치를 켰습니다{PAUSE_UNTIL_PRESS}");
const u8 gText_ExpShareOff[] = _("학습장치를 껐습니다{PAUSE_UNTIL_PRESS}");
ALIGNED(4) const u8 gText_Ghost[] = _("유령");
const u8 gText_Boulderbadge[] = _("회색배지");
const u8 gText_Cascadebadge[] = _("블루배지");
const u8 gText_Thunderbadge[] = _("오렌지배지");
const u8 gText_Rainbowbadge[] = _("무지개배지");
const u8 gText_Soulbadge[] = _("핑크배지");
const u8 gText_Marshbadge[] = _("골드배지");
const u8 gText_Volcanobadge[] = _("진홍색배지");
const u8 gText_Earthbadge[] = _("그린배지");
const u8 gText_OakImportantToGetToKnowPokemonThroughly[] = _("OAK: It's important to get to know\nyour POKéMON thoroughly.\p");
const u8 gText_OakThisIsListOfPokemon[] = _("This is a list of your POKéMON,\n{PLAYER}.\pOpen this to check the skills\nand moves of your POKéMON.\pYou also choose POKéMON here if\nyou want to use an item on one.{PAUSE_UNTIL_PRESS}");

const u8 gText_GBPlayerOn[] = _("GB플레이어의 전원을 켰다!\n과거의 소리가 울려퍼진다{PAUSE_UNTIL_PRESS}");
const u8 gText_GBPlayerOff[] = _("GB플레이어의 전원을 껐다!\n정겨운 소리가 서서히 사라진다{PAUSE_UNTIL_PRESS}");

const u8 gText_Sunday[] = _("일요일");
const u8 gText_Monday[] = _("월요일");
const u8 gText_Tuesday[] = _("화요일");
const u8 gText_Wednesday[] = _("수요일");
const u8 gText_Thursday[] = _("목요일");
const u8 gText_Friday[] = _("금요일");
const u8 gText_Saturday[] = _("토요일");
const u8 gText_LoveBall[] =     _("러브볼{CLEAR_TO 35}/ 복슝열매 / (페어리/에스퍼)");
const u8 gText_Lure[] =         _("루어볼{CLEAR_TO 35}/ 복분열매 / (물/드래곤)");
const u8 gText_FriendBall[] =   _("프렌드볼 / 버치열매 / (벌레/풀)");
const u8 gText_Heavy[] =        _("헤비볼{CLEAR_TO 35}/ 오랭열매 / (바위/땅/강철)");
const u8 gText_Moon[] =         _("문볼{CLEAR_TO 35} / 유루열매 / (악/고스트/독)");
const u8 gText_Fast[] =         _("스피드볼 / 배리열매 / (전기/격투/불꽃)");
const u8 gText_LevelBall[] =    _("레벨볼{CLEAR_TO 35}/ 시몬열매 / (노말/비행/얼음)");
const u8 gText_Vermilion[] = _("갈색시티");
const u8 gText_Olivine[] = _("담청시티");
const u8 gText_Floor0[] = _("0층");
const u8 gText_Pal[] = _("동료");
const u8 gText_Underling[] = _("부하");
const u8 gText_Strategy[] = _("작전");
const u8 gText_Training[] = _("육성");
const u8 gText_Cheating[] = _("사기");
const u8 gText_WeakPerson[] = _("약한 사람");
const u8 gText_ToughPerson[] = _("강한 사람");
const u8 gText_Anybody[] = _("누구든지");
const u8 gText_Love2[] = _("애정");
const u8 gText_Violence[] = _("폭력");
const u8 gText_Knowledge[] = _("지시");
const u8 gText_Tough3[] = _("강한 편");
const u8 gText_Weak[] = _("약한 편");
const u8 gText_Both[] = _("어느 쪽이든");
const u8 gText_GreenStone[] = _("초록돌");
const u8 gText_RedStone[] = _("빨간돌");
const u8 gText_BlueStone[] = _("파랑돌");
